import { StyleSheet } from "react-native";
import { colors } from "../../theme/colors";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#f8fafc" },
  scrollContent: { paddingHorizontal: 14, paddingTop: 20, paddingBottom: 90 },
  mapCard: {
    borderWidth: 1, borderColor: "#e2e8f0", borderRadius: 14, overflow: "hidden",
    marginTop: 6, marginBottom: 12, backgroundColor: "#fff",
    shadowColor: "#000", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 6, elevation: 3,
  },
  map: { width: "100%", height: 220 },
  mapLegendRow: {
    borderTopWidth: 1, borderTopColor: "#e2e8f0",
    paddingHorizontal: 10, paddingVertical: 8, backgroundColor: "#f8fafc", gap: 3,
  },
  mapLegendItem: { color: "#475569", fontSize: 11 },
  section: { paddingBottom: 16, marginBottom: 4 },
  sectionTitle: { color: "#111827", fontWeight: "800", fontSize: 28, marginBottom: 4, letterSpacing: -0.6 },
  sectionSubtitle: { color: "#6b7280", fontSize: 14, fontWeight: "400", marginBottom: 18 },
  subsectionTitle: { color: "#334155", fontWeight: "800", fontSize: 14, marginTop: 10, marginBottom: 8 },
  label: { color: "#374151", fontSize: 13, fontWeight: "600", marginBottom: 5, marginTop: 14 },
  input: {
    minHeight: 48, borderRadius: 10, backgroundColor: "#f3f6fc",
    borderWidth: 1.2, borderColor: "#e5e9f2", paddingHorizontal: 14, paddingVertical: 10,
    color: "#111827", fontSize: 14,
  },
  inputDisabled: {
    minHeight: 48, borderRadius: 10, backgroundColor: "#f0f2f7",
    borderWidth: 1.2, borderColor: "#e5e9f2", paddingHorizontal: 14, paddingVertical: 10,
    color: "#6b7280", fontSize: 14,
  },
  textArea: {
    borderWidth: 1, borderColor: "#dbe4f0", borderRadius: 8,
    paddingHorizontal: 10, paddingVertical: 8, color: "#0f172a",
    backgroundColor: "#fff", minHeight: 110, textAlignVertical: "top",
  },
  row: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
  col: { flex: 1, minWidth: 120 },
  rowBetween: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  stateBox: { alignItems: "center", justifyContent: "center", paddingVertical: 18, gap: 8 },
  stateText: { color: "#64748b", fontSize: 13, textAlign: "center" },
  warningBox: {
    borderWidth: 1, borderColor: "#fde68a", backgroundColor: "#fffbeb",
    borderRadius: 12, padding: 12, marginBottom: 10, flexDirection: "row", alignItems: "center", gap: 10,
  },
  warningText: { color: "#854d0e", fontSize: 12, flex: 1 },
  errorBox: {
    borderWidth: 1, borderColor: "#fecaca", backgroundColor: "#fff1f2",
    borderRadius: 12, padding: 12, marginBottom: 10, gap: 8,
  },
  errorText: { color: "#b91c1c", fontSize: 12 },
  successBox: {
    borderWidth: 1, borderColor: "#86efac", backgroundColor: "#f0fdf4",
    borderRadius: 12, padding: 12, marginBottom: 10,
  },
  successText: { color: "#166534", fontSize: 12, fontWeight: "600" },
  btnPrimary: {
    flex: 1, minHeight: 50, borderRadius: 12, overflow: "hidden",
    shadowColor: "#3f6cf6", shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.3, shadowRadius: 6, elevation: 3,
  },
  btnGradient: {
    flex: 1, minHeight: 50, borderRadius: 12, alignItems: "center",
    justifyContent: "center", paddingHorizontal: 14,
  },
  btnPressed: { opacity: 0.88 },
  btnPrimaryText: { color: "#fff", fontWeight: "800", fontSize: 15.5 },
  btnPrimarySmall: {
    minHeight: 34, paddingHorizontal: 10, borderRadius: 8,
    backgroundColor: colors.accent, alignItems: "center", justifyContent: "center",
  },
  btnPrimarySmallText: { color: "#fff", fontWeight: "700", fontSize: 12 },
  btnSecondary: {
    minHeight: 46, paddingHorizontal: 18, borderRadius: 12,
    borderWidth: 1.5, borderColor: "#cbd5e1", backgroundColor: "#fff",
    alignItems: "center", justifyContent: "center", minWidth: 100,
  },
  btnSecondaryText: { color: "#475569", fontWeight: "700", fontSize: 14 },
  btnSuccess: {
    flex: 1, minHeight: 50, borderRadius: 12, overflow: "hidden",
    shadowColor: colors.success, shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.3, shadowRadius: 6, elevation: 3,
  },
  btnSuccessText: { color: "#fff", fontWeight: "800", fontSize: 15.5 },
  btnDisabledWrapper: { shadowOpacity: 0, elevation: 0 },
  btnOutline: {
    marginTop: 12, minHeight: 44, borderWidth: 1.5, borderColor: colors.accent,
    borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#eff6ff",
  },
  btnOutlineText: { color: colors.accent, fontWeight: "700", fontSize: 14 },
  btnDanger: {
    minHeight: 36, borderRadius: 8, alignItems: "center",
    justifyContent: "center", backgroundColor: colors.danger, paddingHorizontal: 10,
  },
  btnDangerText: { color: "#fff", fontWeight: "700", fontSize: 12 },
  btnDangerSmall: {
    minHeight: 40, paddingHorizontal: 12, borderRadius: 8,
    alignItems: "center", justifyContent: "center", backgroundColor: colors.danger,
  },
  btnDangerSmallText: { color: "#fff", fontWeight: "700", fontSize: 13 },
  btnBack: {
    flexDirection: "row", alignItems: "center", gap: 5,
    paddingVertical: 10, paddingHorizontal: 12, borderRadius: 10,
    backgroundColor: "#f1f5f9", minWidth: 90, justifyContent: "center",
  },
  btnBackText: { color: "#475569", fontWeight: "700", fontSize: 14 },
  btnPrimaryFull: {
    flex: 1, minHeight: 50, borderRadius: 12, overflow: "hidden",
    shadowColor: "#3f6cf6", shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.3, shadowRadius: 6, elevation: 3,
  },
  footerButtons: {
    flexDirection: "row", justifyContent: "space-between", alignItems: "center",
    paddingVertical: 14, paddingHorizontal: 14, gap: 10,
    borderTopWidth: 1, borderTopColor: "#e2e8f0", backgroundColor: "#f8fafc",
  },
  suggestionsWrap: { borderWidth: 1, borderColor: "#dbe4f0", borderRadius: 8, overflow: "hidden", marginTop: 6 },
  suggestionItem: {
    paddingHorizontal: 10, paddingVertical: 9,
    borderBottomWidth: 1, borderBottomColor: "#e2e8f0", backgroundColor: "#fff",
  },
  suggestionTitle: { color: "#0f172a", fontSize: 13, fontWeight: "600" },
  suggestionSub: { color: "#64748b", fontSize: 11, marginTop: 2 },
  inputSearchWrap: {
    flexDirection: "row", alignItems: "center", minHeight: 50, borderRadius: 12,
    backgroundColor: "#f3f6fc", borderWidth: 1.2, borderColor: "#e5e9f2", paddingHorizontal: 14,
  },
  inputSearchFocused: { borderColor: colors.accent, backgroundColor: "#f0f4ff" },
  inputSearchField: { flex: 1, minHeight: 48, color: "#111827", fontSize: 14 },
  searchDropdown: {
    marginTop: 6, borderRadius: 14, backgroundColor: "#fff",
    borderWidth: 1, borderColor: "#e5e9f2",
    shadowColor: "#000", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.10, shadowRadius: 12,
    elevation: 6, overflow: "hidden",
  },
  searchEmptyState: { alignItems: "center", paddingVertical: 22, gap: 8 },
  searchEmptyText: { color: "#94a3b8", fontSize: 13 },
  searchResultItem: {
    flexDirection: "row", alignItems: "center",
    paddingHorizontal: 14, paddingVertical: 13, gap: 12, backgroundColor: "#fff",
  },
  searchResultItemBorder: { borderBottomWidth: 1, borderBottomColor: "#f1f5f9" },
  searchResultItemPressed: { backgroundColor: "#f5f8ff" },
  searchResultAvatar: {
    width: 38, height: 38, borderRadius: 19,
    backgroundColor: "#eff6ff", alignItems: "center", justifyContent: "center",
  },
  searchResultAvatarText: { color: colors.accent, fontSize: 12, fontWeight: "800" },
  searchResultContent: { flex: 1 },
  searchResultTitle: { color: "#111827", fontSize: 14, fontWeight: "600" },
  searchResultHighlight: { color: colors.accent, fontWeight: "800" },
  searchResultSub: { color: "#64748b", fontSize: 12, marginTop: 2 },
  listWrap: {
    borderWidth: 1, borderColor: "#e2e8f0", borderRadius: 14, overflow: "hidden",
    shadowColor: "#000", shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 3, elevation: 1,
  },
  listItem: {
    paddingHorizontal: 10, paddingVertical: 10,
    borderBottomWidth: 1, borderBottomColor: "#f1f5f9", backgroundColor: "#fff",
  },
  listItemCompact: {
    paddingHorizontal: 10, paddingVertical: 8, borderWidth: 1, borderColor: "#e2e8f0",
    borderRadius: 8, marginTop: 6, flexDirection: "row", alignItems: "center",
    justifyContent: "space-between", gap: 8, backgroundColor: "#fff",
  },
  listItemTitle: { color: "#0f172a", fontSize: 13, fontWeight: "600", flex: 1 },
  listItemSub: { color: "#64748b", fontSize: 11, marginTop: 2 },
  modalOverlay: {
    flex: 1, backgroundColor: "rgba(2,6,23,0.55)",
    alignItems: "center", justifyContent: "center", padding: 14,
  },
  modalCard: {
    width: "100%", maxHeight: "74%", borderRadius: 12, backgroundColor: "#fff",
    borderWidth: 1, borderColor: "#e2e8f0", padding: 12, gap: 10,
  },
  modalCardLarge: {
    width: "100%", maxHeight: "90%", borderRadius: 12, backgroundColor: "#fff",
    borderWidth: 1, borderColor: "#e2e8f0", padding: 12,
  },
  modalTitle: { color: "#0f172a", fontSize: 16, fontWeight: "800", marginBottom: 8 },
  modalListItem: { paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: "#e2e8f0" },
  modalListItemText: { color: "#334155", fontSize: 13 },
  modalActions: {
    flexDirection: "row", justifyContent: "space-between",
    alignItems: "center", gap: 8, marginTop: 14, marginBottom: 4,
  },
  selectWrap: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  optionChip: {
    borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 999,
    paddingHorizontal: 10, paddingVertical: 7, backgroundColor: "#fff",
  },
  optionChipAtivo: { borderColor: colors.accent, backgroundColor: "#eff6ff" },
  optionChipText: { color: "#334155", fontSize: 12, fontWeight: "600" },
  optionChipTextAtivo: { color: colors.accent },
  hintText: { color: "#64748b", fontSize: 12, marginTop: 6 },
  photoRow: {
    flexDirection: "row", alignItems: "center", gap: 8, marginTop: 6,
    borderWidth: 1, borderColor: "#e2e8f0", borderRadius: 8, padding: 6, backgroundColor: "#fff",
  },
  photoThumb: { width: 44, height: 44, borderRadius: 6 },
  photoName: { flex: 1, color: "#334155", fontSize: 12 },
});
