version: '3.8'
services:
  api-site:
    build: .
    ports:
      - "3011:3011"
    environment:
      - DB_USER=bellasistemas
      - DB_PASSWORD=bella147123
      - DB_CONNECT=192.168.0.10:1521/XE
    volumes:
      - ./arquivodeintegracaofornecedor:/app/arquivodeintegracaofornecedor
      - ./src/documentos:/app/src/documentos
      - ./src/remessas:/app/src/remessas
      - ./src/certificados:/app/src/certificados
    restart: unless-stopped
