flyway.locations=filesystem:./flyway/sql
flyway.validateMigrationNaming=true
flyway.validateOnMigrate=true
flyway.connectRetries=10
flyway.cleanDisabled=true
flyway.baselineOnMigrate=true
flyway.baselineVersion=0
flyway.baselineDescription=existing schema baseline