-- =============================================================================
-- V1.0 - BASELINE SCHEMA
-- Estado do banco em 30/04/2026 antes do controle de versao.
-- NAO e executado em bancos existentes (baselineOnMigrate=true no flyway.conf).
-- Em bancos novos, cria toda a estrutura no schema do usuario conectado.
-- =============================================================================

CREATE TABLE API_LOG (
    ID_LOG         NUMBER,
    DATA_HORA      DATE DEFAULT SYSDATE,
    IP_CLIENTE     VARCHAR2(500),
    DISPOSITIVO    VARCHAR2(2000),
    METODO_HTTP    VARCHAR2(10),
    ENDPOINT       VARCHAR2(255),
    HEADERS        CLOB,
    REQUEST_BODY   CLOB,
    STATUS_CODIGO  NUMBER,
    RESPONSE_BODY  CLOB,
    TEMPO_EXECUCAO NUMBER(10,3),
    ERRO           CLOB
);

CREATE TABLE BKP_BSTAB_VISITACLIENTE (
    ID_VISITA                   NUMBER(*,0),
    ID_PROMOTOR                 NUMBER(*,0),
    ID_GRUPO_EMPRESA            NUMBER(*,0),
    ID_CLIENTE_ERP              NUMBER(*,0),
    DTCHECKIN                   DATE,
    DTCHECKOUT                  DATE,
    PRO_LATITUDE_CHECKIN        VARCHAR2(80),
    PRO_LONGITUDE_CHECKIN       VARCHAR2(80),
    CLI_LATITUDE                VARCHAR2(80),
    CLI_LONGITUDE               VARCHAR2(80),
    DISTANCIA_ATEDIMENTO        NUMBER(15,2),
    PRO_LATITUDE_CHECKOUT       VARCHAR2(80),
    PRO_LONGITUDE_CHECKOUT      VARCHAR2(80),
    ID_JUSTIFICATIVADISTANCIA   NUMBER(*,0),
    REPONSAVELATENDIMENTOLOCAL  VARCHAR2(200)
);

CREATE TABLE BKP_BSTAB_VISITACLIENTE_ATV (
    ID_VISITA      NUMBER(*,0),
    ID_ATIVIDADE   NUMBER(*,0),
    ID_VETERINARIO NUMBER(*,0),
    TELEFONE       VARCHAR2(100),
    HOUVEVENDA     VARCHAR2(1),
    REALIZADO      VARCHAR2(1),
    COMENTARIO     BLOB,
    ID_EVIDENCIA   NUMBER(*,0),
    ID_EQUIPE      NUMBER(*,0),
    QTPESSOAS      NUMBER(*,0),
    FEZQUIZ        VARCHAR2(1)
);

CREATE TABLE BSTAB_ANALISE_IMPORT_DESPESA (
    ID              NUMBER NOT NULL,
    CNPJ_FILIAL     VARCHAR2(14) NOT NULL,
    CPF_FUNCIONARIO VARCHAR2(11) NOT NULL,
    VALOR           NUMBER(15,2) NOT NULL,
    CONTA           VARCHAR2(20) NOT NULL,
    DATALANCAMENTO  VARCHAR2(8) NOT NULL,
    DATAPAGAMENTO   VARCHAR2(8) NOT NULL,
    DATAGERACAO     VARCHAR2(8) NOT NULL,
    HISTORICO       VARCHAR2(255) NOT NULL,
    IDLEITURA       NUMBER(*,0),
    ID_USUARIOENV   NUMBER(*,0),
    DESCRICAOENV    VARCHAR2(800),
    DATAENV         DATE,
    ID_ITEM         NUMBER(*,0),
    NUMSOLICITACAO  NUMBER(*,0),
    CONSTRAINT PK_BSTAB_ANALISE_IMPORT PRIMARY KEY (ID) ENABLE
);

CREATE INDEX IDX_BSTAB_CNPJ_FILIAL     ON BSTAB_ANALISE_IMPORT_DESPESA (CNPJ_FILIAL);
CREATE INDEX IDX_BSTAB_CONTA           ON BSTAB_ANALISE_IMPORT_DESPESA (CONTA);
CREATE INDEX IDX_BSTAB_CPF_FUNCIONARIO ON BSTAB_ANALISE_IMPORT_DESPESA (CPF_FUNCIONARIO);
CREATE INDEX IDX_BSTAB_DATALANCAMENTO  ON BSTAB_ANALISE_IMPORT_DESPESA (DATALANCAMENTO);

CREATE OR REPLACE TRIGGER TRG_PRE_ANALISE_IMPORT_DESPESA
BEFORE INSERT ON BSTAB_ANALISE_IMPORT_DESPESA
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := SEQ_PRE_ANALISE_IMPORT_DESPESA.NEXTVAL;
    END IF;
END;
/
ALTER TRIGGER TRG_PRE_ANALISE_IMPORT_DESPESA ENABLE;

CREATE TABLE BSTAB_ARQUIVOS (
    ID_ARQUIVO       NUMBER(*,0),
    ID_ROTINA        VARCHAR2(100),
    ID_RELACIONAL    NUMBER(*,0),
    FILE_PATH        VARCHAR2(4000),
    DATA             DATE DEFAULT SYSDATE,
    ID_GRUPO_EMPRESA NUMBER(*,0)
);

CREATE TABLE BSTAB_ATIVIDADEPROMOTOR (
    ID_ATIVIDADE     NUMBER(*,0),
    DESCRICAO        VARCHAR2(200),
    ATIVA            VARCHAR2(1),
    ID_GRUPO_EMPRESA NUMBER(*,0)
);

CREATE TABLE BSTAB_BANCO (
    ID_BANCO                  NUMBER(*,0),
    BANCO                     VARCHAR2(200),
    ID_BANCO_ERP              NUMBER(*,0),
    CONTA                     VARCHAR2(20),
    AGENCIA                   VARCHAR2(20),
    DEVELOPER_APPLICATION_KEY VARCHAR2(999),
    CHAVEBASIC                VARCHAR2(999)
);

CREATE TABLE BSTAB_CADARQINTFORNEC (
    ID_INTFORNEC     NUMBER(*,0),
    NOMEDOARQUIVO    VARCHAR2(200),
    PSQL             BLOB,
    ID_FORNECERP     NUMBER(*,0),
    ID_GRUPO_EMPRESA NUMBER(*,0),
    ID_FUNCULTALT    NUMBER(*,0),
    DTULTALT         DATE,
    ID_FILIALERP     NUMBER(*,0),
    BASEDEDADOS      VARCHAR2(2),
    TIPODOARQUIVO    VARCHAR2(20),
    STATUS           VARCHAR2(1),
    SEPARADOR        VARCHAR2(1),
    GERARCOLUNA      VARCHAR2(1)
);

CREATE TABLE BSTAB_CAIXABANCO (
    ID_BANCO      NUMBER(*,0),
    ID_BANCO_ERP  NUMBER(*,0),
    CAIXABANCO    VARCHAR2(200),
    ID_FILIAL_ERP NUMBER(*,0)
);

CREATE TABLE BSTAB_CAMPOSPARAFORMULARIO (
    ID_CAMPO    NUMBER(*,0),
    CAMPO       VARCHAR2(200),
    TYPE        VARCHAR2(200),
    PLACEHOLDER VARCHAR2(200)
);

CREATE TABLE BSTAB_CAMPOSTELA (
    ID_ROTINA   NUMBER(*,0),
    ID_TELA     NUMBER(*,0),
    ID_CAMPO    NUMBER(*,0),
    ATIVO       VARCHAR2(1),
    OBRIGATORIO VARCHAR2(1)
);

CREATE TABLE BSTAB_CENTRODECUSTO (
    ID_CENTRODECUSTO     NUMBER(*,0) NOT NULL,
    DESCRICAO            VARCHAR2(200),
    ID_CENTRODECUSTO_ERP VARCHAR2(100),
    ID_GRUPO_EMPRESA     NUMBER(*,0),
    CONSTRAINT PK_ID_CENTRODECUSTO PRIMARY KEY (ID_CENTRODECUSTO) ENABLE
);

COMMENT ON COLUMN BSTAB_CENTRODECUSTO.ID_CENTRODECUSTO     IS 'Codigo centro de custo';
COMMENT ON COLUMN BSTAB_CENTRODECUSTO.DESCRICAO             IS 'Descricao do centro de custo';
COMMENT ON COLUMN BSTAB_CENTRODECUSTO.ID_CENTRODECUSTO_ERP  IS 'Codigo do centro de custo no ERP';
COMMENT ON COLUMN BSTAB_CENTRODECUSTO.ID_GRUPO_EMPRESA       IS 'Codigo da empresa';

CREATE TABLE BSTAB_CLIENTEVENDA (
    IDCLIENTEVENDA    NUMBER(*,0),
    CLIENTE           VARCHAR2(300),
    CGC               VARCHAR2(80),
    CONTATO           VARCHAR2(80),
    EMAIL             VARCHAR2(100),
    LATITUDE          VARCHAR2(80),
    LONGITUDE         VARCHAR2(80),
    ENDERECO          VARCHAR2(300),
    NUMEROCASA        VARCHAR2(80),
    BAIRRO            VARCHAR2(200),
    CIDADE            VARCHAR2(200),
    CEP               VARCHAR2(20),
    ESTADO            VARCHAR2(2),
    IDCLIENTEVENDAERP NUMBER(*,0),
    IDGRUPOEMPRESA    NUMBER(*,0),
    DATAINSERIDO      DATE DEFAULT SYSDATE
);

CREATE TABLE BSTAB_COMBUSTIVELVEICULO (
    ID_COMBUSTIVEL   NUMBER(*,0),
    COMBUSTIVEL      VARCHAR2(100),
    ID_GRUPO_EMPRESA NUMBER(*,0)
);

COMMENT ON TABLE  BSTAB_COMBUSTIVELVEICULO                  IS 'tabela cadastro de combustivel';
COMMENT ON COLUMN BSTAB_COMBUSTIVELVEICULO.ID_COMBUSTIVEL   IS 'Codigo do combustivel do veiculo';
COMMENT ON COLUMN BSTAB_COMBUSTIVELVEICULO.COMBUSTIVEL       IS 'Descricao do combustivel do veiculo';
COMMENT ON COLUMN BSTAB_COMBUSTIVELVEICULO.ID_GRUPO_EMPRESA IS 'Codigo do grupo de empresa';

CREATE TABLE BSTAB_CONTAGERENCIAL (
    ID_CONTA         NUMBER(*,0) NOT NULL,
    DESCRICAO        VARCHAR2(100),
    ID_CONTAERP      NUMBER(*,0),
    ID_GRUPO_EMPRESA NUMBER(*,0),
    CONSTRAINT PK_ID_CONTA PRIMARY KEY (ID_CONTA) ENABLE
);

COMMENT ON COLUMN BSTAB_CONTAGERENCIAL.ID_CONTA         IS 'Codigo da conta';
COMMENT ON COLUMN BSTAB_CONTAGERENCIAL.DESCRICAO         IS 'Descricao da conta';
COMMENT ON COLUMN BSTAB_CONTAGERENCIAL.ID_CONTAERP       IS 'Codigo da conta ERP';
COMMENT ON COLUMN BSTAB_CONTAGERENCIAL.ID_GRUPO_EMPRESA  IS 'Codigo da empresa';

CREATE TABLE BSTAB_EMPRESAS (
    ID_EMPRESA                NUMBER(*,0) NOT NULL,
    RAZAOSOCIAL               VARCHAR2(100),
    FANTARIA                  VARCHAR2(100),
    CNPJ_CPF                  VARCHAR2(14),
    EMAIL                     VARCHAR2(100),
    CONTATO                   VARCHAR2(20),
    DTCADASTRO                DATE DEFAULT SYSDATE,
    ID_ERP                    NUMBER(*,0),
    DTINATIVO                 DATE,
    ID_GRUPO_EMPRESA          NUMBER(*,0),
    CEP                       VARCHAR2(30),
    RUA                       VARCHAR2(200),
    NUMERO                    NUMBER(*,0),
    UF                        VARCHAR2(2),
    CIDADE                    VARCHAR2(100),
    BAIRRO                    VARCHAR2(100),
    DEVELOPER_APPLICATION_KEY VARCHAR2(500),
    CHAVEBASIC                VARCHAR2(500),
    CELULAR                   VARCHAR2(20),
    CONSTRAINT PK_ID_EMPRESA PRIMARY KEY (ID_EMPRESA) ENABLE
);

COMMENT ON COLUMN BSTAB_EMPRESAS.ID_EMPRESA        IS 'Codigo da empresa';
COMMENT ON COLUMN BSTAB_EMPRESAS.RAZAOSOCIAL        IS 'Razao social da empresa';
COMMENT ON COLUMN BSTAB_EMPRESAS.FANTARIA            IS 'Nome Fantasia da empresa';
COMMENT ON COLUMN BSTAB_EMPRESAS.CNPJ_CPF            IS 'CNPJ ou CPF';
COMMENT ON COLUMN BSTAB_EMPRESAS.EMAIL               IS 'Email de contato com a empresa';
COMMENT ON COLUMN BSTAB_EMPRESAS.CONTATO             IS 'Numero de contato com a empresa';
COMMENT ON COLUMN BSTAB_EMPRESAS.DTCADASTRO          IS 'Data do cadastro da empresa';
COMMENT ON COLUMN BSTAB_EMPRESAS.ID_ERP              IS 'Codigo da empresa no ERP';
COMMENT ON COLUMN BSTAB_EMPRESAS.DTINATIVO            IS 'Data de inativacao da empresa';
COMMENT ON COLUMN BSTAB_EMPRESAS.ID_GRUPO_EMPRESA    IS 'Codigo do Grupo de Empresas';

CREATE TABLE BSTAB_ENVIASMS (
    NUMERO        VARCHAR2(50),
    SERVICO       VARCHAR2(100),
    MENSAGEM      VARCHAR2(400),
    NOME_CAMPANHA VARCHAR2(100),
    CODIFICACAO   VARCHAR2(1),
    DATAGERADA    DATE DEFAULT SYSDATE,
    DATAENVIADA   DATE
);

CREATE TABLE BSTAB_EQUIPE (
    ID_EQUIPE        NUMBER(*,0),
    EQUIPE           VARCHAR2(100),
    TIPO_EQUIPE      VARCHAR2(100),
    ID_GRUPO_EMPRESA NUMBER(*,0)
);

CREATE TABLE BSTAB_EXTRATOCAIXA_ARQUIVOS (
    ID              NUMBER(10,0) NOT NULL,
    NOME_ARQUIVO    VARCHAR2(255),
    HASH_ARQUIVO    VARCHAR2(64),
    STATUS          VARCHAR2(20),
    DATA_CRIACAO    DATE DEFAULT SYSDATE,
    DATA_PROCESSADO DATE,
    ERRO            CLOB
);

CREATE TABLE BSTAB_EXTRATOCAIXA_HEADER_ARQ (
    ID               NUMBER(10,0),
    HASH_ARQUIVO     VARCHAR2(64),
    LINHA_ARQUIVO    NUMBER(10,0),
    BANCO            VARCHAR2(3),
    LOTE             VARCHAR2(4),
    REGISTRO         VARCHAR2(1),
    TIPOINSCRICAO    VARCHAR2(1),
    NUMEROINSCRICAO  VARCHAR2(14),
    CONVENIO         VARCHAR2(20),
    AGENCIA          VARCHAR2(5),
    DVAGENCIA        VARCHAR2(1),
    CONTA            VARCHAR2(12),
    DVCONTA          VARCHAR2(1),
    DVAGECONTA       VARCHAR2(1),
    NOME             VARCHAR2(30),
    NOMEBANCO        VARCHAR2(30),
    CODIGOARQUIVO    VARCHAR2(1),
    DATAARQUIVO      DATE,
    SEQUENCIAARQUIVO VARCHAR2(6),
    LAYOUTARQUIVO    VARCHAR2(3),
    DENSIDADEARQUIVO VARCHAR2(5)
);

CREATE TABLE BSTAB_EXTRATOCAIXA_HEADER_LOTE (
    ID                          NUMBER(10,0),
    HASH_ARQUIVO                VARCHAR2(64),
    LINHA_ARQUIVO               NUMBER(10,0),
    BANCO                       VARCHAR2(3),
    LOTE                        VARCHAR2(4),
    REGISTRO                    VARCHAR2(1),
    OPERACAO                    VARCHAR2(1),
    SERVICO                     VARCHAR2(2),
    FORMALANCAMENTO             VARCHAR2(2),
    LAYOUT                      VARCHAR2(3),
    TIPOINSCRICAO               VARCHAR2(1),
    NUMEROINSCRICAO             VARCHAR2(14),
    CONVENIO                    VARCHAR2(20),
    AGENCIA                     VARCHAR2(5),
    DVAGENCIA                   VARCHAR2(1),
    CONTA                       VARCHAR2(12),
    DVCONTA                     VARCHAR2(1),
    DVAGECONTA                  VARCHAR2(1),
    NOME                        VARCHAR2(30),
    DATASALDOINICIAL            DATE,
    VALORSALDOINCIAL            NUMBER(15,2),
    SITUACAOSALDOINICIAL        VARCHAR2(1),
    STATUSSALDOINICIAL          VARCHAR2(1),
    TIPOMOEDASALDOINICIAL       VARCHAR2(3),
    SEQUENCIAEXTRATOSALDOINCIAL VARCHAR2(5)
);

CREATE TABLE BSTAB_EXTRATOCAIXA_REGISTROS (
    ID                  NUMBER(10,0) NOT NULL,
    HASH_ARQUIVO        VARCHAR2(64),
    LINHA_ARQUIVO       NUMBER(10,0),
    BANCO               VARCHAR2(3),
    AGENCIA             VARCHAR2(5),
    CONTA               VARCHAR2(12),
    REGISTRO            VARCHAR2(1),
    NUMERODOREGISTRO    VARCHAR2(5),
    SEGMENTO            VARCHAR2(1),
    TIPOINSCRICAO       VARCHAR2(1),
    NUMEROINSCRICAO     VARCHAR2(14),
    CONVENIO            VARCHAR2(20),
    DVAGENCIA           VARCHAR2(1),
    DVCONTA             VARCHAR2(1),
    DVAGECONTA          VARCHAR2(1),
    NOME                VARCHAR2(30),
    DATALANC            DATE,
    VALORLANC           NUMBER(15,2),
    TIPOLANC            VARCHAR2(1),
    CATEGORIALANC       VARCHAR2(3),
    CODIGOHISTORICOLANC VARCHAR2(4),
    HISTORICOLANC       VARCHAR2(25),
    NUMERODOCUMENTOLANC VARCHAR2(20)
);

CREATE TABLE BSTAB_EXTRATOCAIXA_TRAILERARQ (
    ID                    NUMBER(10,0),
    HASH_ARQUIVO          VARCHAR2(64),
    LINHA_ARQUIVO         NUMBER(10,0),
    QTLOTE_TOTAIS         NUMBER(6,0),
    QTREGISTRO_TOTAIS     NUMBER(15,2),
    QTCONTASCONCIL_TOTAIS NUMBER(6,0)
);

CREATE TABLE BSTAB_EXTRATOCAIXA_TRAILERLOTE (
    ID                  NUMBER(10,0),
    HASH_ARQUIVO        VARCHAR2(64),
    LINHA_ARQUIVO       NUMBER(10,0),
    BANCO               VARCHAR2(3),
    LOTE                VARCHAR2(4),
    REGISTRO            VARCHAR2(1),
    TIPOINSCRICAO       VARCHAR2(1),
    NUMEROINSCRICAO     VARCHAR2(14),
    CONVENIO            VARCHAR2(20),
    AGENCIA             VARCHAR2(5),
    DVAGENCIA           VARCHAR2(1),
    CONTA               VARCHAR2(12),
    DVCONTA             VARCHAR2(1),
    DVAGECONTA          VARCHAR2(1),
    NOME                VARCHAR2(30),
    VALORLIMITE         NUMBER(15,2),
    VALORBLOQUEADO      NUMBER(15,2),
    DATASALDOFINAL      DATE,
    VALORSALDOFINAL     NUMBER(15,2),
    SITUACAOSALDOFINAL  VARCHAR2(1),
    STATUSSALDOFINAL    VARCHAR2(1),
    QTREGISTRO_TOTAIS   VARCHAR2(6),
    VALORDEBITO_TOTAIS  NUMBER(15,2),
    VALORCREDITO_TOTAIS NUMBER(15,2)
);

CREATE TABLE BSTAB_EXTRATOCX_CATEGORIA_LC (
    ID       NUMBER(*,0),
    DECRICAO VARCHAR2(100)
);

CREATE TABLE BSTAB_FORMADEPAGAMENTO (
    ID_FORMADEPAGAMENTO NUMBER(*,0),
    FORMADEPAGAMENTO    VARCHAR2(100)
);

CREATE TABLE BSTAB_FORNECEDOR (
    ID_FORNEC        NUMBER(*,0) NOT NULL,
    FORNECEDOR       VARCHAR2(100),
    ID_FORNEC_ERP    NUMBER(*,0),
    ID_GRUPO_EMPRESA NUMBER(*,0),
    CNPJ_CPF         VARCHAR2(80),
    CONSTRAINT PK_IDFORNEC PRIMARY KEY (ID_FORNEC) ENABLE
);

COMMENT ON COLUMN BSTAB_FORNECEDOR.ID_FORNEC        IS 'Codigo do fornecedor no intranet';
COMMENT ON COLUMN BSTAB_FORNECEDOR.FORNECEDOR        IS 'Nome do fornecedor';
COMMENT ON COLUMN BSTAB_FORNECEDOR.ID_FORNEC_ERP     IS 'Codigo do fornecedor no ERP';
COMMENT ON COLUMN BSTAB_FORNECEDOR.ID_GRUPO_EMPRESA  IS 'Codigo do Servidor ou grupo de empresa';
COMMENT ON COLUMN BSTAB_FORNECEDOR.CNPJ_CPF           IS 'Cnpj ou Cpf do fornecedor';

CREATE TABLE BSTAB_GRUPO_EMPRESA (
    ID_GRUPO_EMPRESA NUMBER(*,0),
    GRUPO_EMPRESA    VARCHAR2(200)
);

COMMENT ON TABLE  BSTAB_GRUPO_EMPRESA                   IS 'tabela cadastro de grupo de empresa';
COMMENT ON COLUMN BSTAB_GRUPO_EMPRESA.ID_GRUPO_EMPRESA  IS 'Codigo do grupo de empresa';
COMMENT ON COLUMN BSTAB_GRUPO_EMPRESA.GRUPO_EMPRESA      IS 'Descricao do grupo de empresa';

CREATE TABLE BSTAB_HOSTCLIENTES (
    ID_GRUPO_EMPRESAS NUMBER(*,0),
    HOST              VARCHAR2(200)
);

CREATE TABLE BSTAB_INSTITUICAOBANCARIA (
    ID_BANCO NUMBER(*,0),
    BANCO    VARCHAR2(100)
);

CREATE TABLE BSTAB_INTEGRACAO (
    ID_SERVIDOR                  VARCHAR2(200),
    ID_INTEGRACAO                NUMBER(*,0),
    INTEGRACAO                   VARCHAR2(100),
    DATAHORA_PROXIMA_ATUALIZACAO DATE,
    INTERVALOMINUTOS             NUMBER(*,0),
    REALIZARINTEGRACAO           VARCHAR2(1),
    METODO                       VARCHAR2(20)
);

CREATE TABLE BSTAB_ITEM (
    ID_ITEM          NUMBER(*,0) NOT NULL,
    DESCRICAO        VARCHAR2(100),
    DESCRICAO2       VARCHAR2(100),
    DTCADASTRO       DATE DEFAULT SYSDATE,
    ID_USERCADASTRO  NUMBER(*,0),
    ID_GRUPO_EMPRESA NUMBER(*,0),
    TIPODEITEM       VARCHAR2(5),
    ID_ITEM_ERP      NUMBER(*,0),
    ID_FORNEC_ERP    NUMBER(*,0),
    CONSTRAINT PK_ID_ITEM PRIMARY KEY (ID_ITEM) ENABLE
);

CREATE TABLE BSTAB_JUSTIFICATIVA (
    IDJUSTIFICATIVA  NUMBER(*,0),
    JUSTIFICATIVA    VARCHAR2(200),
    ATIVO            VARCHAR2(1),
    ID_GRUPO_EMPRESA NUMBER(*,0)
);

CREATE TABLE BSTAB_LOGAJUSTECLIENTE (
    ID_GRUPO_EMPRESA NUMBER(*,0),
    ID_CLIENTE       NUMBER(*,0),
    TIPOAJUSTE       VARCHAR2(10),
    DATAAJUSTE       DATE DEFAULT SYSDATE,
    ID_USUARIO       NUMBER(*,0)
);

CREATE TABLE BSTAB_LOGSISTEMA (
    DATA DATE DEFAULT SYSDATE,
    LOG  VARCHAR2(200),
    HOST VARCHAR2(200)
);

CREATE TABLE BSTAB_MARCAVEICULO (
    ID_MARCA         NUMBER(*,0),
    MARCA            VARCHAR2(100),
    ID_GRUPO_EMPRESA NUMBER(*,0)
);

COMMENT ON TABLE  BSTAB_MARCAVEICULO                   IS 'tabela cadastro da marca do veiculo';
COMMENT ON COLUMN BSTAB_MARCAVEICULO.ID_MARCA          IS 'Codigo da marca do veiculo';
COMMENT ON COLUMN BSTAB_MARCAVEICULO.MARCA              IS 'Descricao da marca do veiculo';
COMMENT ON COLUMN BSTAB_MARCAVEICULO.ID_GRUPO_EMPRESA  IS 'Codigo do grupo de empresa';

CREATE TABLE BSTAB_MODELOVEICULO (
    ID_MODELO        NUMBER(*,0),
    MODELO           VARCHAR2(100),
    ID_GRUPO_EMPRESA NUMBER(*,0)
);

COMMENT ON TABLE  BSTAB_MODELOVEICULO                   IS 'tabela do cadastro de modelo do veiculo';
COMMENT ON COLUMN BSTAB_MODELOVEICULO.ID_MODELO         IS 'Codigo do modelo do veiculo';
COMMENT ON COLUMN BSTAB_MODELOVEICULO.MODELO             IS 'Descricao do modelo do veiculo';
COMMENT ON COLUMN BSTAB_MODELOVEICULO.ID_GRUPO_EMPRESA  IS 'codigo do grupo de empresa';

CREATE TABLE BSTAB_MODULOS (
    ID_MODULO NUMBER(*,0) NOT NULL,
    MODULO    VARCHAR2(100),
    DTCRIACAO DATE DEFAULT SYSDATE,
    CONSTRAINT PK_ID_MODULO PRIMARY KEY (ID_MODULO) ENABLE
);

COMMENT ON COLUMN BSTAB_MODULOS.ID_MODULO  IS 'Codigo do modulo de rotinas';
COMMENT ON COLUMN BSTAB_MODULOS.MODULO      IS 'Descricao do modulo';
COMMENT ON COLUMN BSTAB_MODULOS.DTCRIACAO   IS 'Data de criacao do modulo';

CREATE TABLE BSTAB_NOTIFICACAO (
    ID_NOTIFICACAO NUMBER NOT NULL,
    TITULO         VARCHAR2(200),
    MENSAGEM       CLOB,
    ID_USUARIO     NUMBER,
    DATA_CRIACAO   DATE DEFAULT SYSDATE,
    LIDA           NUMBER(1,0) DEFAULT 0,
    ID_REMETENTE   NUMBER(*,0)
);

CREATE TABLE BSTAB_ORACMENTOMENSALDADOS (
    CODCONTA         NUMBER(*,0),
    CONTA            VARCHAR2(200),
    M1               NUMBER(15,2),
    M2               NUMBER(15,2),
    M3               NUMBER(15,2),
    M4               NUMBER(15,2),
    M5               NUMBER(15,2),
    M6               NUMBER(15,2),
    M7               NUMBER(15,2),
    M8               NUMBER(15,2),
    M9               NUMBER(15,2),
    M10              NUMBER(15,2),
    M11              NUMBER(15,2),
    M12              NUMBER(15,2),
    ANO              NUMBER(*,0),
    ID_EMPRESA_ERP   NUMBER(*,0),
    ID_GRUPO_EMPRESA NUMBER(*,0),
    ID_USUARIO_ERP   NUMBER(*,0),
    DATALANC         DATE DEFAULT SYSDATE
);

CREATE TABLE BSTAB_ORDENADORES (
    ID_USUARIO_ERP   NUMBER(*,0),
    ID_EMPRESA_ERP   NUMBER(*,0),
    ID_CONTA_ERP     NUMBER(*,0),
    ID_GRUPO_EMPRESA NUMBER(*,0)
);

CREATE TABLE BSTAB_PARAMETROGERAL (
    ID_PARAMENTRO NUMBER(*,0),
    PARAMETRO     VARCHAR2(100),
    VALOR         VARCHAR2(200)
);

CREATE TABLE BSTAB_PARAMETROPORGRUPOEMPRESA (
    ID_PARAMENTRO    NUMBER(*,0),
    PARAMETRO        VARCHAR2(300),
    VALOR            VARCHAR2(4000),
    ID_GRUPO_EMPRESA NUMBER(*,0)
);

CREATE TABLE BSTAB_PERMISOES (
    ID_ROTINA  NUMBER(*,0),
    ID_USUARIO NUMBER(*,0),
    PERMITIR   VARCHAR2(1),
    CONSTRAINT CK_PERMITIR CHECK (PERMITIR IN ('S','N')) ENABLE
);

COMMENT ON COLUMN BSTAB_PERMISOES.ID_ROTINA  IS 'Codigo da rotina';
COMMENT ON COLUMN BSTAB_PERMISOES.ID_USUARIO  IS 'Codigo do usuario';
COMMENT ON COLUMN BSTAB_PERMISOES.PERMITIR    IS 'Paramentro de acesso: (S) permitir ou (N) nao permitir';

CREATE TABLE BSTAB_ROTINAS (
    ID_ROTINA     NUMBER(*,0) NOT NULL,
    ROTINA        VARCHAR2(100),
    VERSAO        VARCHAR2(30),
    DTCRIACAO     DATE DEFAULT SYSDATE,
    DTATUALIZACAO DATE,
    ID_MODULO     NUMBER(*,0),
    CAMINHO       VARCHAR2(200),
    SCREEN        VARCHAR2(200),
    CONSTRAINT PK_ID_ROTINA PRIMARY KEY (ID_ROTINA) ENABLE
);

ALTER TABLE BSTAB_ROTINAS ADD CONSTRAINT FK_ID_MODULO
    FOREIGN KEY (ID_MODULO) REFERENCES BSTAB_MODULOS (ID_MODULO) ON DELETE CASCADE ENABLE;

COMMENT ON COLUMN BSTAB_ROTINAS.ID_ROTINA      IS 'Codigo da rotina';
COMMENT ON COLUMN BSTAB_ROTINAS.ROTINA          IS 'Descricao da rotina';
COMMENT ON COLUMN BSTAB_ROTINAS.VERSAO          IS 'Versao da rotina';
COMMENT ON COLUMN BSTAB_ROTINAS.DTCRIACAO       IS 'Data de criacao da rotina';
COMMENT ON COLUMN BSTAB_ROTINAS.DTATUALIZACAO   IS 'Data da ultima atualizacao';
COMMENT ON COLUMN BSTAB_ROTINAS.ID_MODULO       IS 'Codigo do modulo que a rotina pertence';
COMMENT ON COLUMN BSTAB_ROTINAS.CAMINHO         IS 'Caminho para direcionamento da pagina';

CREATE TABLE BSTAB_SOLICITADESPESAC (
    NUMSOLICITACAO        NUMBER(*,0) NOT NULL,
    DATASOLICITACAO       DATE DEFAULT SYSDATE,
    ID_SOLICITANTE        NUMBER(*,0),
    ID_FILIALDESPESA      NUMBER(*,0),
    DATAESTIMADA          DATE,
    OBJETIVO              BLOB,
    ID_EMPRESASOLICITANTE NUMBER(*,0),
    STATUS                VARCHAR2(2),
    CODCONTAGERENCIAL     NUMBER(*,0),
    CODCENTRODECUSTO      VARCHAR2(50),
    DATAHORACONTROLADORIA DATE,
    ID_GRUPO_EMPRESA      NUMBER(*,0),
    OBS_ORDENADOR         BLOB,
    DATAHORAORDENADOR     DATE,
    ID_ORDENADOR          NUMBER(*,0),
    ID_USER_CONTROLADORIA NUMBER(*,0),
    ID_FORNECEDOR         NUMBER(*,0),
    DATASICRONIZACAO_ERP  DATE,
    TIPOFORNECEDOR        VARCHAR2(10),
    ID_FORMADEPAGAMENTO   NUMBER(*,0),
    ID_BANCO              NUMBER(*,0),
    AGENCIA               VARCHAR2(100),
    CONTABANCARIA         VARCHAR2(100),
    OPERACAO              VARCHAR2(100),
    CHAVEPIX              VARCHAR2(800),
    TIPODEDESPESA         VARCHAR2(10),
    TIPOCONTA             VARCHAR2(1),
    ID_ROTINA_INTEGRACAO  NUMBER(*,0),
    OBS_FINANCEIRO        BLOB,
    ID_USER_FINANCEIRO    NUMBER(*,0),
    ID_CAIXABANCO         NUMBER(*,0),
    DATAHORAFINANCEIRO    DATE,
    HISTORICO1            VARCHAR2(200),
    HISTORICO2            VARCHAR2(200)
);

CREATE TABLE BSTAB_SOLICITADESPESAI (
    NUMSOLICITACAO NUMBER(*,0),
    ID_ITEM        NUMBER(*,0),
    QUANTIDADE     NUMBER(15,2),
    VLUNIT         NUMBER(15,2)
);

CREATE TABLE BSTAB_SOLICITADESPESA_RATEIO (
    ID_CENTRODECUSTO VARCHAR2(200),
    PERCENTUAL       NUMBER(15,2),
    VALOR            NUMBER(15,2),
    ID_SOLICITACAO   NUMBER(*,0),
    ID_RATEIO        NUMBER(*,0)
);

CREATE TABLE BSTAB_TIPODECONTABANCARIA (
    ID_TIPOCONTABANCARIA NUMBER(*,0),
    TIPO                 VARCHAR2(100)
);

CREATE TABLE BSTAB_USUARIO_RATEIO (
    ID               NUMBER(*,0),
    ID_CENTRODECUSTO VARCHAR2(100),
    ID_USUARIO       NUMBER(*,0),
    PERRATEIO        NUMBER(15,2)
);

CREATE TABLE BSTAB_USUARIO_SETOR (
    ID_SETOR         NUMBER(*,0) NOT NULL,
    SETOR            VARCHAR2(100),
    ID_SETOR_ERP     NUMBER(*,0),
    ID_GRUPO_EMPRESA NUMBER(*,0),
    CONSTRAINT PK_ID_SETOR PRIMARY KEY (ID_SETOR) ENABLE
);

COMMENT ON TABLE  BSTAB_USUARIO_SETOR                IS 'Tabela referente ao setor do funcionario e usuario';
COMMENT ON COLUMN BSTAB_USUARIO_SETOR.ID_SETOR       IS 'Codigo do setor';
COMMENT ON COLUMN BSTAB_USUARIO_SETOR.SETOR           IS 'Descricao do setor';

CREATE TABLE BSTAB_USUSARIOS (
    ID_USUARIO          NUMBER(*,0) NOT NULL,
    NOME                VARCHAR2(100),
    EMAIL               VARCHAR2(100),
    SENHA               VARCHAR2(30) DEFAULT 'SENHA31032020',
    DTCADASTRO          DATE DEFAULT SYSDATE,
    DTINATIVO           DATE,
    ID_EMPRESA_ERP      NUMBER(*,0),
    ID_USUARIO_ERP      NUMBER(*,0),
    ID_SETOR_ERP        NUMBER(*,0),
    ID_GRUPO_EMPRESA    NUMBER(*,0),
    CPF                 VARCHAR2(30),
    RG                  VARCHAR2(30),
    TELEFONE            VARCHAR2(30),
    CEP                 VARCHAR2(10),
    RUA                 VARCHAR2(100),
    NUMERO              VARCHAR2(10),
    UF                  VARCHAR2(2),
    CIDADE              VARCHAR2(100),
    BAIRRO              VARCHAR2(100),
    COMPLEMENTO         VARCHAR2(500),
    ID_FILIAL_ERP       NUMBER(*,0),
    DATANASCIMENTO      DATE,
    SEXO                VARCHAR2(100),
    NACIONALIDADE       VARCHAR2(100),
    NATURALIDADE        VARCHAR2(100),
    CARGO               VARCHAR2(100),
    DATAADMISSAO        DATE,
    TIPODECONTRATO      VARCHAR2(100),
    CNH                 VARCHAR2(100),
    DATAEXPIRACAOCNH    DATE,
    ID_BANCO            NUMBER(*,0),
    AGENCIA             VARCHAR2(50),
    CONTA               VARCHAR2(50),
    OPERACAO            VARCHAR2(50),
    ID_BANCOTERCEIRO    NUMBER(*,0),
    AGENCIATERCEIRO     VARCHAR2(50),
    CONTATERCEIRO       VARCHAR2(50),
    OPERACAOTERCEIRO    VARCHAR2(50),
    BENEFICIADOTERCEIRO VARCHAR2(100),
    CHAVEPIX            VARCHAR2(500),
    CHAVEPIXTERCEIRO    VARCHAR2(500)
);

CREATE TABLE BSTAB_VALE (
    ID_LANCAMENTO         NUMBER(*,0),
    ID_VALE               NUMBER(*,0),
    ID_FILIAL             NUMBER(*,0),
    DATA_LANCAMENTO       DATE,
    DATA_VENCIMENTO       DATE,
    DATA_BAIXA            DATE,
    ID_FUNC               NUMBER(*,0),
    TIPOLANC              VARCHAR2(1),
    VALOR                 NUMBER(15,2),
    HISTORICO             VARCHAR2(200),
    ID_FUNC_BAIXA         NUMBER(*,0),
    ID_LANCAMENTO_ERP     NUMBER(*,0),
    ID_VICULOSOLCTDESPESA NUMBER(*,0),
    ID_GRUPO_EMPRESA      NUMBER(*,0)
);

CREATE TABLE BSTAB_VEICULO (
    ID_VEICULO       NUMBER(*,0),
    PLACA            VARCHAR2(20),
    RENAVAM          VARCHAR2(100),
    CHASSI           VARCHAR2(100),
    ID_MARCA         NUMBER(*,0),
    ID_MODELO        NUMBER(*,0),
    ANO_FABRICACAO   NUMBER(*,0),
    COR              VARCHAR2(100),
    ID_COMBUSTIVEL   NUMBER(*,0),
    SITUACAO         VARCHAR2(1),
    KMATUAL          NUMBER(*,0),
    ID_GRUPO_EMPRESA NUMBER(*,0),
    ID_VEICULO_ERP   NUMBER(*,0),
    DESCRICAO        VARCHAR2(100),
    DTATUALIZADO     DATE,
    DTSYNC           DATE
);

COMMENT ON TABLE  BSTAB_VEICULO                      IS 'tabela de cadastro de veiculo';
COMMENT ON COLUMN BSTAB_VEICULO.ID_VEICULO           IS 'codigo do veiculo';
COMMENT ON COLUMN BSTAB_VEICULO.PLACA                IS 'placa do veiculo';
COMMENT ON COLUMN BSTAB_VEICULO.RENAVAM              IS 'renavan do veiculo';
COMMENT ON COLUMN BSTAB_VEICULO.CHASSI               IS 'chassi do veiculo';
COMMENT ON COLUMN BSTAB_VEICULO.ID_MARCA             IS 'Codigo da marca do veiculo';
COMMENT ON COLUMN BSTAB_VEICULO.ID_MODELO            IS 'Codigo do modelo do veiculo';
COMMENT ON COLUMN BSTAB_VEICULO.ANO_FABRICACAO       IS 'ano de fabricacao do veiculo';
COMMENT ON COLUMN BSTAB_VEICULO.COR                  IS 'cor do veiculo';
COMMENT ON COLUMN BSTAB_VEICULO.ID_COMBUSTIVEL       IS 'codigo do combustivel';
COMMENT ON COLUMN BSTAB_VEICULO.SITUACAO             IS 'situacao do veiculo';
COMMENT ON COLUMN BSTAB_VEICULO.KMATUAL              IS 'km atual do veiculo';
COMMENT ON COLUMN BSTAB_VEICULO.ID_GRUPO_EMPRESA     IS 'codigo do grupo de empresas';
COMMENT ON COLUMN BSTAB_VEICULO.ID_VEICULO_ERP       IS 'codigo do veiculo em sistemas externos';
COMMENT ON COLUMN BSTAB_VEICULO.DESCRICAO            IS 'descricao do veiculo';
COMMENT ON COLUMN BSTAB_VEICULO.DTATUALIZADO         IS 'data da atualizacao do cadastro';
COMMENT ON COLUMN BSTAB_VEICULO.DTSYNC               IS 'data de sincronizacao com o erp externo';

CREATE TABLE BSTAB_VINCULODESPES_ERP (
    NUMSOLICITACAO_ERP NUMBER(*,0),
    NUMSOLICITACAO     NUMBER(*,0),
    GRUPO_DE_EMPRESA   NUMBER(*,0)
);

CREATE TABLE BSTAB_VISITACLIENTE (
    ID_VISITA                   NUMBER(*,0),
    ID_PROMOTOR                 NUMBER(*,0),
    ID_GRUPO_EMPRESA            NUMBER(*,0),
    ID_CLIENTE                  NUMBER(*,0),
    DTCHECKIN                   DATE,
    DTCHECKOUT                  DATE,
    PRO_LATITUDE_CHECKIN        VARCHAR2(80),
    PRO_LONGITUDE_CHECKIN       VARCHAR2(80),
    CLI_LATITUDE                VARCHAR2(80),
    CLI_LONGITUDE               VARCHAR2(80),
    DISTANCIA_ATEDIMENTO        NUMBER(15,2),
    PRO_LATITUDE_CHECKOUT       VARCHAR2(80),
    PRO_LONGITUDE_CHECKOUT      VARCHAR2(80),
    ID_JUSTIFICATIVADISTANCIA   NUMBER(*,0),
    REPONSAVELATENDIMENTOLOCAL  VARCHAR2(200)
);

COMMENT ON TABLE  BSTAB_VISITACLIENTE                            IS 'visita ao cliente feita pelo promotor';
COMMENT ON COLUMN BSTAB_VISITACLIENTE.ID_VISITA                 IS 'codigo da visita realizada';
COMMENT ON COLUMN BSTAB_VISITACLIENTE.ID_PROMOTOR               IS 'codigo do promotor';
COMMENT ON COLUMN BSTAB_VISITACLIENTE.ID_GRUPO_EMPRESA          IS 'codigo referente ao grupo de empresa';
COMMENT ON COLUMN BSTAB_VISITACLIENTE.ID_CLIENTE                IS 'codigo do cliente no erp';
COMMENT ON COLUMN BSTAB_VISITACLIENTE.DTCHECKIN                 IS 'data de checkin momento que o promotor iniciou a visita';
COMMENT ON COLUMN BSTAB_VISITACLIENTE.DTCHECKOUT                IS 'data de checkout momento em que o promotor finalizou a visita';
COMMENT ON COLUMN BSTAB_VISITACLIENTE.PRO_LATITUDE_CHECKIN      IS 'latitude do promotor no checkin';
COMMENT ON COLUMN BSTAB_VISITACLIENTE.PRO_LONGITUDE_CHECKIN     IS 'longitude do promotor no checkin';
COMMENT ON COLUMN BSTAB_VISITACLIENTE.CLI_LATITUDE              IS 'latitude do cliente cadastrada';
COMMENT ON COLUMN BSTAB_VISITACLIENTE.CLI_LONGITUDE             IS 'longitude do cliente cadastrada';
COMMENT ON COLUMN BSTAB_VISITACLIENTE.DISTANCIA_ATEDIMENTO      IS 'distancia entre cliente e promotor no checkin';
COMMENT ON COLUMN BSTAB_VISITACLIENTE.PRO_LATITUDE_CHECKOUT     IS 'latitude no checkout';
COMMENT ON COLUMN BSTAB_VISITACLIENTE.PRO_LONGITUDE_CHECKOUT    IS 'longitude no checkout';
COMMENT ON COLUMN BSTAB_VISITACLIENTE.ID_JUSTIFICATIVADISTANCIA IS 'codigo da justificativa de distancia';

CREATE TABLE BSTAB_VISITACLIENTE_ATV (
    ID_VISITA    NUMBER(*,0),
    ID_ATIVIDADE NUMBER(*,0),
    VETERINARIO  VARCHAR2(300),
    TELEFONE     VARCHAR2(100),
    HOUVEVENDA   VARCHAR2(1),
    REALIZADO    VARCHAR2(1),
    COMENTARIO   BLOB,
    ID_EVIDENCIA NUMBER(*,0),
    ID_EQUIPE    NUMBER(*,0),
    QTPESSOAS    NUMBER(*,0),
    FEZQUIZ      VARCHAR2(1)
);

CREATE TABLE BSTAB_VISITACLI_ITEM (
    ID_VISITA    NUMBER(*,0),
    ID_ATIVIDADE NUMBER(*,0),
    ID_ITEM      NUMBER(*,0),
    QT           NUMBER,
    TIPOITEM     VARCHAR2(5),
    ID_EVIDENCIA NUMBER(*,0)
);

CREATE TABLE TABELAS_DEV (
    TABELA VARCHAR2(100)
);

CREATE TABLE WEBHOOK_PIX_BOLETO (
    ID                         VARCHAR2(50),
    DATA_REGISTRO              DATE,
    DATA_VENCIMENTO            DATE,
    VALOR_ORIGINAL             NUMBER(15,2),
    VALOR_PAGO_SACADO          NUMBER(15,2),
    NUMERO_CONVENIO            NUMBER(10,0),
    NUMERO_OPERACAO            NUMBER(10,0),
    CARTEIRA_CONVENIO          NUMBER(5,0),
    VARIACAO_CARTEIRA_CONVENIO NUMBER(5,0),
    CODIGO_ESTADO_BAIXA_OP     NUMBER(5,0),
    DATA_LIQUIDACAO            DATE,
    INSTITUICAO_LIQUIDACAO     NUMBER(5,0),
    CANAL_LIQUIDACAO           NUMBER(5,0),
    CODIGO_MODALIDADE_BOLETO   NUMBER(5,0),
    TIPO_PESSOA_PORTADOR       NUMBER(1,0),
    IDENTIDADE_PORTADOR        VARCHAR2(50),
    NOME_PORTADOR              VARCHAR2(100),
    FORMA_PAGAMENTO            NUMBER(2,0),
    JSON_COMPLETO              CLOB,
    DATA_RECEBIDA              DATE DEFAULT SYSDATE
);

-- =============================================================================
-- VIEWS
-- =============================================================================

CREATE OR REPLACE VIEW VWBS_ACOMPANHAMENTODEDESPESA (
    ID_EMPRESA_ERP, CODCONTA, CONTA, ANO,
    M1, GM1, M2, GM2, M3, GM3, M4, GM4, M5, GM5, M6, GM6,
    M7, GM7, M8, GM8, M9, GM9, M10, GM10, M11, GM11, M12, GM12,
    ORCTOTAL, GASTOTOTAL
) AS
SELECT O.ID_EMPRESA_ERP, O.CODCONTA, O.CONTA, O.ANO,
       O.M1,  FBS_RETORNAGASTOMESDESPESA(O.ID_EMPRESA_ERP, O.CODCONTA, O.ID_GRUPO_EMPRESA, '01', O.ANO) GM1,
       O.M2,  FBS_RETORNAGASTOMESDESPESA(O.ID_EMPRESA_ERP, O.CODCONTA, O.ID_GRUPO_EMPRESA, '02', O.ANO) GM2,
       O.M3,  FBS_RETORNAGASTOMESDESPESA(O.ID_EMPRESA_ERP, O.CODCONTA, O.ID_GRUPO_EMPRESA, '03', O.ANO) GM3,
       O.M4,  FBS_RETORNAGASTOMESDESPESA(O.ID_EMPRESA_ERP, O.CODCONTA, O.ID_GRUPO_EMPRESA, '04', O.ANO) GM4,
       O.M5,  FBS_RETORNAGASTOMESDESPESA(O.ID_EMPRESA_ERP, O.CODCONTA, O.ID_GRUPO_EMPRESA, '05', O.ANO) GM5,
       O.M6,  FBS_RETORNAGASTOMESDESPESA(O.ID_EMPRESA_ERP, O.CODCONTA, O.ID_GRUPO_EMPRESA, '06', O.ANO) GM6,
       O.M7,  FBS_RETORNAGASTOMESDESPESA(O.ID_EMPRESA_ERP, O.CODCONTA, O.ID_GRUPO_EMPRESA, '07', O.ANO) GM7,
       O.M8,  FBS_RETORNAGASTOMESDESPESA(O.ID_EMPRESA_ERP, O.CODCONTA, O.ID_GRUPO_EMPRESA, '08', O.ANO) GM8,
       O.M9,  FBS_RETORNAGASTOMESDESPESA(O.ID_EMPRESA_ERP, O.CODCONTA, O.ID_GRUPO_EMPRESA, '09', O.ANO) GM9,
       O.M10, FBS_RETORNAGASTOMESDESPESA(O.ID_EMPRESA_ERP, O.CODCONTA, O.ID_GRUPO_EMPRESA, '10', O.ANO) GM10,
       O.M11, FBS_RETORNAGASTOMESDESPESA(O.ID_EMPRESA_ERP, O.CODCONTA, O.ID_GRUPO_EMPRESA, '11', O.ANO) GM11,
       O.M12, FBS_RETORNAGASTOMESDESPESA(O.ID_EMPRESA_ERP, O.CODCONTA, O.ID_GRUPO_EMPRESA, '12', O.ANO) GM12,
       (O.M1+O.M2+O.M3+O.M4+O.M5+O.M6+O.M7+O.M8+O.M9+O.M10+O.M11+O.M12) ORCTOTAL,
       FBS_RETORNAGASTOANODESPESA(O.ID_EMPRESA_ERP, O.CODCONTA, O.ID_GRUPO_EMPRESA, O.ANO) GASTOTOTAL
  FROM BSTAB_ORACMENTOMENSALDADOS O
 ORDER BY O.CONTA, O.ID_EMPRESA_ERP;

CREATE OR REPLACE VIEW VWBS_ORCAMENTOPORDATA (
    CODCONTA, CONTA, DATAVIGENCIA, VALOR, ID_GRUPO_EMPRESA, ID_EMPRESA_ERP, ID_USUARIO_ERP
) AS
SELECT CODCONTA, CONTA,
       TO_DATE('01/'||MES||'/'||ANO,'DD/MM/YYYY') DATAVIGENCIA,
       VALOR, ID_GRUPO_EMPRESA, ID_EMPRESA_ERP, ID_USUARIO_ERP
FROM BSTAB_ORACMENTOMENSALDADOS
UNPIVOT (
    VALOR FOR MES IN (M1 AS '01', M2 AS '02', M3 AS '03', M4 AS '04',
                      M5 AS '05', M6 AS '06', M7 AS '07', M8 AS '08',
                      M9 AS '09', M10 AS '10', M11 AS '11', M12 AS '12')
) A;

-- =============================================================================
-- FUNCTIONS
-- =============================================================================

CREATE OR REPLACE FUNCTION FBS_RETORNAGASTOANODESPESA(
    P_FILIALERP       IN INTEGER,
    P_CONTAERP        IN INTEGER,
    P_IDGRUPOEMPRESA  IN INTEGER,
    P_ANO             IN VARCHAR2
) RETURN NUMBER IS
    V_VALOR NUMBER;
BEGIN
    V_VALOR := 0;
    SELECT SUM(NVL(I.QUANTIDADE, 0) * NVL(I.VLUNIT, 0))
      INTO V_VALOR
      FROM BSTAB_SOLICITADESPESAC C, BSTAB_SOLICITADESPESAI I
     WHERE C.CODCONTAGERENCIAL = P_CONTAERP
       AND C.NUMSOLICITACAO = I.NUMSOLICITACAO
       AND C.ID_FILIALDESPESA = P_FILIALERP
       AND C.ID_GRUPO_EMPRESA = P_IDGRUPOEMPRESA
       AND TO_CHAR(C.DATAESTIMADA, 'YYYY') = P_ANO;
    RETURN NVL(V_VALOR, 0);
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN 0;
    WHEN OTHERS THEN RETURN NULL;
END FBS_RETORNAGASTOANODESPESA;
/

CREATE OR REPLACE FUNCTION FBS_RETORNAGASTOMESDESPESA(
    P_FILIALERP       IN INTEGER,
    P_CONTAERP        IN INTEGER,
    P_IDGRUPOEMPRESA  IN INTEGER,
    P_MES             IN VARCHAR2,
    P_ANO             IN VARCHAR2
) RETURN NUMBER IS
    V_VALOR NUMBER;
BEGIN
    V_VALOR := 0;
    SELECT SUM(NVL(I.QUANTIDADE, 0) * NVL(I.VLUNIT, 0))
      INTO V_VALOR
      FROM BSTAB_SOLICITADESPESAC C, BSTAB_SOLICITADESPESAI I
     WHERE C.CODCONTAGERENCIAL = P_CONTAERP
       AND C.NUMSOLICITACAO = I.NUMSOLICITACAO
       AND C.ID_FILIALDESPESA = P_FILIALERP
       AND C.ID_GRUPO_EMPRESA = P_IDGRUPOEMPRESA
       AND TO_CHAR(C.DATAESTIMADA, 'MM') = P_MES
       AND TO_CHAR(C.DATAESTIMADA, 'YYYY') = P_ANO;
    RETURN NVL(V_VALOR, 0);
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN 0;
    WHEN OTHERS THEN RETURN NULL;
END FBS_RETORNAGASTOMESDESPESA;
/

-- =============================================================================
-- SEQUENCES
-- =============================================================================

CREATE SEQUENCE BSSEQ_NUMSOLICITACAO
    INCREMENT BY 1 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;

CREATE SEQUENCE SEQ_ID_LEITURA_IMPORT_DESPESA
    INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER;

CREATE SEQUENCE SEQ_PRE_ANALISE_IMPORT_DESPESA
    INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER;
