CREATE TABLE BELLASISTEMAS.BSTAB_INTEGRACAO (
  ID_SERVIDOR                   VARCHAR2(200) NOT NULL,
  ID_INTEGRACAO                 NUMBER(10,0) NOT NULL,
  INTEGRACAO                    VARCHAR2(100) NOT NULL,
  DATAHORA_PROXIMA_ATUALIZACAO  DATE NOT NULL,
  INTERVALOMINUTOS              NUMBER(10,0) NOT NULL,
  REALIZARINTEGRACAO            VARCHAR2(1) NOT NULL,
  METODO                        VARCHAR2(20) NOT NULL,
  CONSTRAINT PK_BSTAB_INTEGRACAO PRIMARY KEY (ID_SERVIDOR, ID_INTEGRACAO),
  CONSTRAINT CK_BSTAB_INTEGRACAO_REALIZAR CHECK (REALIZARINTEGRACAO IN ('S', 'N'))
);

CREATE INDEX BELLASISTEMAS.IX_BSTAB_INTEGRACAO_DATA
  ON BELLASISTEMAS.BSTAB_INTEGRACAO (DATAHORA_PROXIMA_ATUALIZACAO);

CREATE INDEX BELLASISTEMAS.IX_BSTAB_INTEGRACAO_REALIZAR
  ON BELLASISTEMAS.BSTAB_INTEGRACAO (REALIZARINTEGRACAO);