-- =============================================================================
-- V1.1 - UPGRADE COMPLETO A PARTIR DA V1.0
-- Delta entre V1.0__baseline_schema.sql e DLLATUAL.sql
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 0) Colunas novas em tabelas existentes
-- -----------------------------------------------------------------------------
DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'BSTAB_FORMADEPAGAMENTO'
       AND COLUMN_NAME = 'ID_BANCODOBRASIL';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BSTAB_FORMADEPAGAMENTO ADD (ID_BANCODOBRASIL VARCHAR2(100))';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists
      FROM USER_INDEXES
     WHERE TABLE_NAME = 'BSTAB_FORMADEPAGAMENTO'
       AND INDEX_NAME = 'IDX_BSTAB_FORMADEPAGTO_BB';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_BSTAB_FORMADEPAGTO_BB ON BSTAB_FORMADEPAGAMENTO (ID_BANCODOBRASIL)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'BSTAB_NOTIFICACAO'
       AND COLUMN_NAME = 'DADOS_TABELA';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BSTAB_NOTIFICACAO ADD (DADOS_TABELA CLOB)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'BSTAB_USUSARIOS'
       AND COLUMN_NAME = 'FOTO';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BSTAB_USUSARIOS ADD (FOTO VARCHAR2(500))';
    END IF;
END;
/

-- -----------------------------------------------------------------------------
-- 1) Tabelas BB
-- -----------------------------------------------------------------------------
DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BB_CREDENCIAIS';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BB_CREDENCIAIS (
                ID_FILIAL                 NUMBER,
                AGENCIA                   VARCHAR2(10),
                CONTA                     VARCHAR2(20),
                CLIENT_ID                 VARCHAR2(200),
                CLIENT_SECRET             VARCHAR2(2000),
                APP_KEY                   VARCHAR2(2000),
                ACCESS_TOKEN              CLOB,
                TOKEN_EXPIRACAO           DATE,
                ULTIMA_DATA_CONSULTA      DATE,
                MOEDAAPLICACAOAUTOMATICA  VARCHAR2(20),
                ID_USUARIO_ERP            NUMBER(*,0),
                CODCONTACRED              NUMBER(*,0),
                CODCONTADEB               NUMBER(*,0),
                CAMINHODOCERTIFICADO      VARCHAR2(2000),
                SENHACERTIFICADO          VARCHAR2(2000),
                CONSTRAINT PK_BB_CREDENCIAIS PRIMARY KEY (ID_FILIAL)
            )
        ]';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BB_EXTRATO';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BB_EXTRATO (
                ID                           NUMBER(20,0),
                DATA_CRIACAO                 DATE DEFAULT SYSDATE NOT NULL,
                DV_CONTA_CONTRAPARTIDA       VARCHAR2(5),
                NUMERO_CONTA_CONTRAPARTIDA   VARCHAR2(20),
                CODIGO_AGENCIA_CONTRAPARTIDA NUMBER(10,0),
                CODIGO_BANCO_CONTRAPARTIDA   NUMBER(10,0),
                TIPO_PESSOA                  CHAR(1),
                CPF_CNPJ                     VARCHAR2(20),
                INFO_COMPLEMENTAR            VARCHAR2(200),
                TIPO                         CHAR(1),
                VALOR                        NUMBER(18,2),
                DESCRICAO                    VARCHAR2(200),
                CODIGO_HISTORICO             NUMBER(10,0),
                NUMERO_LOTE                  NUMBER(20,0),
                CODIGO_AGENCIA_ORIGEM        NUMBER(10,0),
                DATA_MOVIMENTO               DATE,
                DATA_LANCAMENTO              DATE,
                NUMERO_DOCUMENTO             VARCHAR2(50),
                ID_FILIAL                    NUMBER(10,0),
                INDICADORTIPOLANCAMENTO      VARCHAR2(5),
                STATUS_PROCESSAMENTO         NUMBER(1,0) DEFAULT 0,
                DATA_PROCESSAMENTO           DATE,
                ERRO_PROCESSAMENTO           VARCHAR2(500),
                CONSTRAINT PK_BB_EXTRATO PRIMARY KEY (ID),
                CONSTRAINT UK_BB_EXTRATO_IDEMPOTENCIA UNIQUE (
                    ID_FILIAL,
                    NUMERO_DOCUMENTO,
                    NUMERO_LOTE,
                    DATA_LANCAMENTO,
                    VALOR,
                    TIPO
                )
            )
        ]';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BB_LOG';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BB_LOG (
                ID                NUMBER,
                DATA_LOG          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                NIVEL             VARCHAR2(10) NOT NULL,
                MODULO            VARCHAR2(50) NOT NULL,
                ID_FILIAL         NUMBER,
                MENSAGEM          VARCHAR2(1000),
                DETALHE_ERRO      CLOB,
                TEMPO_EXECUCAO_MS NUMBER,
                AMBIENTE          VARCHAR2(20),
                SERVIDOR          VARCHAR2(100),
                ID_BB_EXTRATO     NUMBER(*,0),
                CONSTRAINT PK_BB_LOG PRIMARY KEY (ID)
            )
        ]';
    END IF;
END;
/

-- -----------------------------------------------------------------------------
-- 2) Comunicacao, comentario, enquete e reacao
-- -----------------------------------------------------------------------------
DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BSTAB_COMUNICADOS';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BSTAB_COMUNICADOS (
                ID_COMUNICADO      NUMBER NOT NULL,
                TITULO             VARCHAR2(200) NOT NULL,
                CONTEUDO           VARCHAR2(4000),
                TIPO               VARCHAR2(50) DEFAULT 'AVISO',
                FOTOS              CLOB,
                ID_USUARIO_AUTOR   NUMBER NOT NULL,
                NOME_AUTOR         VARCHAR2(200),
                SETOR_AUTOR        VARCHAR2(200),
                DATA_PUBLICACAO    DATE DEFAULT SYSDATE,
                ATIVO              NUMBER(1,0) DEFAULT 1,
                ID_GRUPO_EMPRESA   NUMBER NOT NULL,
                DATA_DISPONIVEL    DATE,
                DATA_EXPIRACAO     DATE,
                PERMITE_COMENTARIO NUMBER(1,0) DEFAULT 0,
                CONSTRAINT PK_BSTAB_COMUNICADOS PRIMARY KEY (ID_COMUNICADO)
            )
        ]';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BSTAB_COMENTARIO';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BSTAB_COMENTARIO (
                ID_COMENTARIO     NUMBER,
                ID_COMUNICADO     NUMBER NOT NULL,
                ID_USUARIO        NUMBER NOT NULL,
                NOME_USUARIO      VARCHAR2(200),
                FOTO_USUARIO      VARCHAR2(500),
                TEXTO             VARCHAR2(2000) NOT NULL,
                DATA_COMENTARIO   DATE DEFAULT SYSDATE,
                ATIVO             NUMBER(1,0) DEFAULT 1,
                ID_COMENTARIO_PAI NUMBER DEFAULT NULL,
                CONSTRAINT PK_BSTAB_COMENTARIO PRIMARY KEY (ID_COMENTARIO)
            )
        ]';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BSTAB_ENQUETE';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BSTAB_ENQUETE (
                ID_ENQUETE       NUMBER,
                ID_COMUNICADO    NUMBER NOT NULL,
                PERGUNTA         VARCHAR2(500) NOT NULL,
                MULTIPLA_ESCOLHA NUMBER(1,0) DEFAULT 0 NOT NULL,
                CONSTRAINT PK_BSTAB_ENQUETE PRIMARY KEY (ID_ENQUETE)
            )
        ]';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BSTAB_ENQUETE_OPCAO';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BSTAB_ENQUETE_OPCAO (
                ID_OPCAO   NUMBER,
                ID_ENQUETE NUMBER NOT NULL,
                TEXTO      VARCHAR2(300) NOT NULL,
                ORDEM      NUMBER DEFAULT 0,
                CONSTRAINT PK_BSTAB_ENQUETE_OPCAO PRIMARY KEY (ID_OPCAO)
            )
        ]';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BSTAB_ENQUETE_VOTO';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BSTAB_ENQUETE_VOTO (
                ID_VOTO    NUMBER,
                ID_ENQUETE NUMBER NOT NULL,
                ID_OPCAO   NUMBER NOT NULL,
                ID_USUARIO NUMBER NOT NULL,
                DATA_VOTO  DATE DEFAULT SYSDATE,
                CONSTRAINT PK_BSTAB_ENQUETE_VOTO PRIMARY KEY (ID_VOTO)
            )
        ]';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BSTAB_REACAO';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BSTAB_REACAO (
                ID_REACAO     NUMBER,
                ID_COMUNICADO NUMBER NOT NULL,
                ID_USUARIO    NUMBER NOT NULL,
                TIPO          VARCHAR2(10) NOT NULL,
                DATA_REACAO   DATE DEFAULT SYSDATE,
                CONSTRAINT PK_BSTAB_REACAO PRIMARY KEY (ID_REACAO),
                CONSTRAINT UQ_REACAO UNIQUE (ID_COMUNICADO, ID_USUARIO)
            )
        ]';
    END IF;
END;
/

-- -----------------------------------------------------------------------------
-- 3) IA
-- -----------------------------------------------------------------------------
DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BSTAB_IA_AGENTE';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BSTAB_IA_AGENTE (
                ID_AGENTE        NUMBER(15,0) NOT NULL,
                TIPO_AGENTE      VARCHAR2(40) NOT NULL,
                NOME_AGENTE      VARCHAR2(120) NOT NULL,
                REGRAS_GERAIS    CLOB NOT NULL,
                STATUS           CHAR(1) DEFAULT 'A' NOT NULL,
                ID_USUARIO       NUMBER(10,0) DEFAULT 0 NOT NULL,
                ID_GRUPO_EMPRESA NUMBER(10,0) DEFAULT 0 NOT NULL,
                DT_CADASTRO      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                DT_ATUALIZACAO   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT PK_BSTAB_IA_AGENTE PRIMARY KEY (ID_AGENTE),
                CONSTRAINT CK_BSTAB_IA_AGENTE_STATUS CHECK (STATUS IN ('A', 'I'))
            )
        ]';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IX_BSTAB_IA_AGENTE_STATUS';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IX_BSTAB_IA_AGENTE_STATUS ON BSTAB_IA_AGENTE (STATUS, DT_ATUALIZACAO)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = 'UX_BSTAB_IA_AGENTE_CTX';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_BSTAB_IA_AGENTE_CTX ON BSTAB_IA_AGENTE (TIPO_AGENTE, ID_USUARIO, ID_GRUPO_EMPRESA)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BSTAB_IA_AGENTE_TABELA';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BSTAB_IA_AGENTE_TABELA (
                ID_AGENTE_TABELA NUMBER(15,0) NOT NULL,
                ID_AGENTE        NUMBER(15,0) NOT NULL,
                NOME_TABELA      VARCHAR2(120) NOT NULL,
                NOME_NEGOCIO     VARCHAR2(200),
                DESCRICAO        VARCHAR2(300),
                COLUNAS_DEF      CLOB NOT NULL,
                RELACIONAMENTOS  CLOB,
                OBSERVACOES      CLOB,
                STATUS           CHAR(1) DEFAULT 'A' NOT NULL,
                DT_CADASTRO      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                DT_ATUALIZACAO   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT PK_BSTAB_IA_AGENTE_TABELA PRIMARY KEY (ID_AGENTE_TABELA),
                CONSTRAINT CK_BSTAB_IA_AG_TAB_STATUS CHECK (STATUS IN ('A', 'I'))
            )
        ]';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'BSTAB_IA_AGENTE_TABELA'
       AND CONSTRAINT_NAME = 'FK_BSTAB_IA_AGENTE_TABELA_AG';

    IF v_exists = 0 THEN
        BEGIN
            EXECUTE IMMEDIATE 'ALTER TABLE BSTAB_IA_AGENTE_TABELA ADD CONSTRAINT FK_BSTAB_IA_AGENTE_TABELA_AG FOREIGN KEY (ID_AGENTE) REFERENCES BSTAB_IA_AGENTE (ID_AGENTE)';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -2275 THEN
                    RAISE;
                END IF;
        END;
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = 'UX_BSTAB_IA_AG_TAB_AG_TB';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_BSTAB_IA_AG_TAB_AG_TB ON BSTAB_IA_AGENTE_TABELA (ID_AGENTE, NOME_TABELA)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IX_BSTAB_IA_AG_TAB_STATUS';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IX_BSTAB_IA_AG_TAB_STATUS ON BSTAB_IA_AGENTE_TABELA (STATUS, NOME_TABELA)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BSTAB_IA_CONVERSA';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BSTAB_IA_CONVERSA (
                ID_CONVERSA          NUMBER(15,0) NOT NULL,
                CONVERSATION_ID      VARCHAR2(100 CHAR) NOT NULL,
                ID_USUARIO           NUMBER(15,0) DEFAULT 0 NOT NULL,
                ID_GRUPO_EMPRESA     NUMBER(15,0) DEFAULT 0 NOT NULL,
                RESUMO_CONTEXTO      CLOB,
                ID_ULTIMA_MSG_RESUMO NUMBER(15,0) DEFAULT 0 NOT NULL,
                STATUS               CHAR(1) DEFAULT 'A' NOT NULL,
                DT_CADASTRO          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                DT_ULTIMA_INTERACAO  TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT PK_BSTAB_IA_CONVERSA PRIMARY KEY (ID_CONVERSA),
                CONSTRAINT UK_BSTAB_IA_CONVERSA UNIQUE (CONVERSATION_ID, ID_USUARIO, ID_GRUPO_EMPRESA),
                CONSTRAINT CK_BSTAB_IA_CONVERSA_STATUS CHECK (STATUS IN ('A', 'I'))
            )
        ]';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IX_IA_CONV_DT_ULT_INT';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IX_IA_CONV_DT_ULT_INT ON BSTAB_IA_CONVERSA (DT_ULTIMA_INTERACAO)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BSTAB_IA_CONVERSA_FEEDBACK';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BSTAB_IA_CONVERSA_FEEDBACK (
                ID_FEEDBACK    NUMBER(15,0) NOT NULL,
                ID_CONVERSA    NUMBER(15,0) NOT NULL,
                ID_MSG_CLIENTE VARCHAR2(120 CHAR),
                TIPO_FEEDBACK  VARCHAR2(10 CHAR) NOT NULL,
                COMENTARIO     VARCHAR2(600 CHAR),
                DT_CADASTRO    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT PK_BSTAB_IA_CONV_FEEDBACK PRIMARY KEY (ID_FEEDBACK),
                CONSTRAINT CK_BSTAB_IA_CONV_FEEDBACK_TIPO CHECK (TIPO_FEEDBACK IN ('up', 'down'))
            )
        ]';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'BSTAB_IA_CONVERSA_FEEDBACK'
       AND CONSTRAINT_NAME = 'FK_BSTAB_IA_CONV_FEEDBACK_CONV';

    IF v_exists = 0 THEN
        BEGIN
            EXECUTE IMMEDIATE 'ALTER TABLE BSTAB_IA_CONVERSA_FEEDBACK ADD CONSTRAINT FK_BSTAB_IA_CONV_FEEDBACK_CONV FOREIGN KEY (ID_CONVERSA) REFERENCES BSTAB_IA_CONVERSA (ID_CONVERSA) ON DELETE CASCADE';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -2275 THEN
                    RAISE;
                END IF;
        END;
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IX_IA_CONV_FB_CONVERSA';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IX_IA_CONV_FB_CONVERSA ON BSTAB_IA_CONVERSA_FEEDBACK (ID_CONVERSA, DT_CADASTRO)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BSTAB_IA_CONVERSA_MSG';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BSTAB_IA_CONVERSA_MSG (
                ID_MENSAGEM     NUMBER(15,0) NOT NULL,
                ID_CONVERSA     NUMBER(15,0) NOT NULL,
                PAPEL           VARCHAR2(20 CHAR) NOT NULL,
                TIPO_MENSAGEM   VARCHAR2(30 CHAR) NOT NULL,
                CONTEUDO_JSON   CLOB NOT NULL,
                RESUMO_CONTEXTO VARCHAR2(1500 CHAR),
                DT_CADASTRO     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT PK_BSTAB_IA_CONVERSA_MSG PRIMARY KEY (ID_MENSAGEM),
                CONSTRAINT CK_BSTAB_IA_CONV_MSG_PAPEL CHECK (PAPEL IN ('user', 'assistant'))
            )
        ]';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'BSTAB_IA_CONVERSA_MSG'
       AND CONSTRAINT_NAME = 'FK_BSTAB_IA_CONV_MSG_CONV';

    IF v_exists = 0 THEN
        BEGIN
            EXECUTE IMMEDIATE 'ALTER TABLE BSTAB_IA_CONVERSA_MSG ADD CONSTRAINT FK_BSTAB_IA_CONV_MSG_CONV FOREIGN KEY (ID_CONVERSA) REFERENCES BSTAB_IA_CONVERSA (ID_CONVERSA) ON DELETE CASCADE';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -2275 THEN
                    RAISE;
                END IF;
        END;
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IX_BSTAB_IA_CONV_MSG_CONVERSA';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IX_BSTAB_IA_CONV_MSG_CONVERSA ON BSTAB_IA_CONVERSA_MSG (ID_CONVERSA, ID_MENSAGEM)';
    END IF;
END;
/

-- -----------------------------------------------------------------------------
-- 4) Log de integracao
-- -----------------------------------------------------------------------------
DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BSTAB_LOG_INTEGRACAO';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BSTAB_LOG_INTEGRACAO (
                ID_LOG           NUMBER,
                ID_SERVIDOR      NUMBER,
                ID_INTEGRACAO    NUMBER,
                INTEGRACAO       VARCHAR2(100),
                HOST             VARCHAR2(500),
                DATA_HORA_INICIO DATE,
                DATA_HORA_FIM    DATE,
                DURACAO_SEGUNDOS NUMBER,
                STATUS           VARCHAR2(1),
                QTD_RECEBIDOS    NUMBER DEFAULT 0,
                QTD_INSERIDOS    NUMBER DEFAULT 0,
                QTD_ATUALIZADOS  NUMBER DEFAULT 0,
                QTD_ERROS        NUMBER DEFAULT 0,
                MENSAGEM_ERRO    VARCHAR2(4000),
                CONSTRAINT PK_BSTAB_LOG_INTEGRACAO PRIMARY KEY (ID_LOG)
            )
        ]';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BSTAB_LOG_INTEGRACAO_DETALHE';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BSTAB_LOG_INTEGRACAO_DETALHE (
                ID_DETALHE         NUMBER,
                ID_LOG             NUMBER,
                OPERACAO           VARCHAR2(1),
                ID_REGISTRO_ERP    VARCHAR2(100),
                DESCRICAO_REGISTRO VARCHAR2(500),
                MENSAGEM_ERRO      VARCHAR2(4000),
                DATA_HORA          DATE DEFAULT SYSDATE,
                CONSTRAINT PK_BSTAB_LOG_INTEG_DET PRIMARY KEY (ID_DETALHE)
            )
        ]';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'BSTAB_LOG_INTEGRACAO_DETALHE'
       AND CONSTRAINT_NAME = 'FK_BSTAB_LOG_INTEG_DET_LOG';

    IF v_exists = 0 THEN
        BEGIN
            EXECUTE IMMEDIATE 'ALTER TABLE BSTAB_LOG_INTEGRACAO_DETALHE ADD CONSTRAINT FK_BSTAB_LOG_INTEG_DET_LOG FOREIGN KEY (ID_LOG) REFERENCES BSTAB_LOG_INTEGRACAO (ID_LOG)';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -2275 THEN
                    RAISE;
                END IF;
        END;
    END IF;
END;
/

-- -----------------------------------------------------------------------------
-- 5) Subpermissoes
-- -----------------------------------------------------------------------------
DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BSTAB_ROTINA_SUBPERMISSOES';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BSTAB_ROTINA_SUBPERMISSOES (
                ID_SUBPERMISSAO NUMBER(10,0) NOT NULL,
                ID_ROTINA       NUMBER(10,0) NOT NULL,
                DESCRICAO       VARCHAR2(150) NOT NULL,
                ORDEM           NUMBER(10,0) DEFAULT 0 NOT NULL,
                ATIVO           CHAR(1) DEFAULT 'S' NOT NULL,
                DT_CADASTRO     DATE DEFAULT SYSDATE NOT NULL,
                DT_ALTERACAO    DATE,
                CONSTRAINT PK_BSTAB_ROTINA_SUBPERMISSOES PRIMARY KEY (ID_SUBPERMISSAO),
                CONSTRAINT CK_BSTAB_ROT_SUB_ATIVO CHECK (ATIVO IN ('S', 'N'))
            )
        ]';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'BSTAB_ROTINA_SUBPERMISSOES'
       AND CONSTRAINT_NAME = 'FK_BSTAB_ROT_SUB_ROTINA';

    IF v_exists = 0 THEN
        BEGIN
            EXECUTE IMMEDIATE 'ALTER TABLE BSTAB_ROTINA_SUBPERMISSOES ADD CONSTRAINT FK_BSTAB_ROT_SUB_ROTINA FOREIGN KEY (ID_ROTINA) REFERENCES BSTAB_ROTINAS (ID_ROTINA)';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -2275 THEN
                    RAISE;
                END IF;
        END;
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = 'UK_BSTAB_ROT_SUB_ROTINA_DESC';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UK_BSTAB_ROT_SUB_ROTINA_DESC ON BSTAB_ROTINA_SUBPERMISSOES (ID_ROTINA, DESCRICAO)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists
      FROM USER_TRIGGERS
     WHERE TRIGGER_NAME = 'TRG_BSTAB_ROTINA_SUBPERMISSOES';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE OR REPLACE TRIGGER TRG_BSTAB_ROTINA_SUBPERMISSOES
            BEFORE INSERT ON BSTAB_ROTINA_SUBPERMISSOES
            FOR EACH ROW
            BEGIN
                IF :NEW.ID_SUBPERMISSAO IS NULL THEN
                    SELECT SEQ_BSTAB_ROTINA_SUBPERMISSOES.NEXTVAL
                      INTO :NEW.ID_SUBPERMISSAO
                      FROM DUAL;
                END IF;

                IF :NEW.DT_CADASTRO IS NULL THEN
                    :NEW.DT_CADASTRO := SYSDATE;
                END IF;
            END;
        ]';
    END IF;
END;
/

ALTER TRIGGER TRG_BSTAB_ROTINA_SUBPERMISSOES ENABLE;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BSTAB_USUARIO_SUBPERMISSOES';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BSTAB_USUARIO_SUBPERMISSOES (
                ID_USUARIO      NUMBER(10,0) NOT NULL,
                ID_SUBPERMISSAO NUMBER(10,0) NOT NULL,
                PERMITIR        CHAR(1) DEFAULT 'N' NOT NULL,
                DT_CADASTRO     DATE DEFAULT SYSDATE NOT NULL,
                DT_ALTERACAO    DATE,
                CONSTRAINT PK_BSTAB_USUARIO_SUBPERMISSOES PRIMARY KEY (ID_USUARIO, ID_SUBPERMISSAO),
                CONSTRAINT CK_BSTAB_USU_SUB_PERMITIR CHECK (PERMITIR IN ('S', 'N'))
            )
        ]';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'BSTAB_USUARIO_SUBPERMISSOES'
       AND CONSTRAINT_NAME = 'FK_BSTAB_USU_SUB_SUBPERM';

    IF v_exists = 0 THEN
        BEGIN
            EXECUTE IMMEDIATE 'ALTER TABLE BSTAB_USUARIO_SUBPERMISSOES ADD CONSTRAINT FK_BSTAB_USU_SUB_SUBPERM FOREIGN KEY (ID_SUBPERMISSAO) REFERENCES BSTAB_ROTINA_SUBPERMISSOES (ID_SUBPERMISSAO)';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -2275 THEN
                    RAISE;
                END IF;
        END;
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IX_BST_USU_SUB_01';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IX_BST_USU_SUB_01 ON BSTAB_USUARIO_SUBPERMISSOES (ID_USUARIO)';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IX_BST_USU_SUB_02';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IX_BST_USU_SUB_02 ON BSTAB_USUARIO_SUBPERMISSOES (ID_SUBPERMISSAO)';
    END IF;
END;
/

-- -----------------------------------------------------------------------------
-- 6) Historico da solicitacao de despesa
-- -----------------------------------------------------------------------------
DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'BSTAB_SOLICITADESPESA_HISTORICO';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE BSTAB_SOLICITADESPESA_HISTORICO (
                ID_HISTORICO     NUMBER(19,0) NOT NULL,
                NUMSOLICITACAO   NUMBER(19,0) NOT NULL,
                ID_GRUPO_EMPRESA NUMBER(19,0),
                ETAPA            VARCHAR2(100) NOT NULL,
                STATUS_ANTES     VARCHAR2(100),
                STATUS_DEPOIS    VARCHAR2(100) NOT NULL,
                ID_USUARIO       NUMBER(19,0),
                NOME_USUARIO     VARCHAR2(200),
                OBSERVACAO       CLOB,
                DATAHORA         DATE DEFAULT SYSDATE NOT NULL,
                CONSTRAINT PK_BSTAB_SOLICDESP_HIST PRIMARY KEY (ID_HISTORICO)
            )
        ]';
    END IF;
END;
/

DECLARE
    v_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_INDEXES WHERE INDEX_NAME = 'IX_SOLICDESP_HIST_SOLIC_DATA';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IX_SOLICDESP_HIST_SOLIC_DATA ON BSTAB_SOLICITADESPESA_HISTORICO (NUMSOLICITACAO, DATAHORA)';
    END IF;
END;
/

-- -----------------------------------------------------------------------------
-- 7) Sequences novas
-- -----------------------------------------------------------------------------
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='BSSEQ_COMENTARIO'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE BSSEQ_COMENTARIO INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='BSSEQ_COMUNICADO'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE BSSEQ_COMUNICADO INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='BSSEQ_ENQUETE'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE BSSEQ_ENQUETE INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='BSSEQ_ENQUETE_OPCAO'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE BSSEQ_ENQUETE_OPCAO INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='BSSEQ_ENQUETE_VOTO'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE BSSEQ_ENQUETE_VOTO INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='BSSEQ_REACAO'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE BSSEQ_REACAO INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='BSSEQ_IA_AGENTE'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE BSSEQ_IA_AGENTE INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='BSSEQ_IA_AGENTE_TABELA'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE BSSEQ_IA_AGENTE_TABELA INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='BSSEQ_IA_CONVERSA'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE BSSEQ_IA_CONVERSA INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='BSSEQ_IA_CONVERSA_MSG'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE BSSEQ_IA_CONVERSA_MSG INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='BSSEQ_IA_CONV_FEEDBACK'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE BSSEQ_IA_CONV_FEEDBACK INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_BB_EXTRATO'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_BB_EXTRATO INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_BB_LOG'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_BB_LOG INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_BSTAB_LOG_INTEGRACAO'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_BSTAB_LOG_INTEGRACAO INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_BSTAB_LOG_INTEG_DETALHE'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_BSTAB_LOG_INTEG_DETALHE INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_BSTAB_ROTINA_SUBPERMISSOES'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_BSTAB_ROTINA_SUBPERMISSOES INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_BST_ROT_SUB'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_BST_ROT_SUB INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_SOLICITADESPESA_HISTORICO'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_SOLICITADESPESA_HISTORICO INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
