-- =============================================================================
-- V1.2 - SEED DADOS DE REFERENCIA
-- Carrega dados essenciais de configuracao de forma idempotente.
-- Preencha os blocos USING (...) com os valores da base atual.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1) BSTAB_FORMADEPAGAMENTO
-- Chave natural: ID_FORMADEPAGAMENTO
-- -----------------------------------------------------------------------------
MERGE INTO BSTAB_FORMADEPAGAMENTO d
USING (
    SELECT 1 AS ID_FORMADEPAGAMENTO, 'DINHEIRO' AS FORMADEPAGAMENTO, NULL AS ID_BANCODOBRASIL FROM DUAL
    UNION ALL SELECT 2, 'PIX TRANSFERENCIA', '45' FROM DUAL
    UNION ALL SELECT 3, 'CONTA CORRENTE', '1' FROM DUAL
    UNION ALL SELECT 4, 'DOC/TED', '3' FROM DUAL
    UNION ALL SELECT 5, 'POUPANCA', '5' FROM DUAL
    UNION ALL SELECT 6, 'TED OUTRA TITULARIDADE', '41' FROM DUAL
    UNION ALL SELECT 7, 'TED MESMA TITULARIDADE', '43' FROM DUAL
    UNION ALL SELECT 8, 'PIX QR CODE', '47' FROM DUAL
    UNION ALL SELECT 9, 'BOLETO', '30' FROM DUAL
    UNION ALL SELECT 10, 'BOLETO OUTROS BANCOS', '31' FROM DUAL
) s
ON (d.ID_FORMADEPAGAMENTO = s.ID_FORMADEPAGAMENTO)
WHEN MATCHED THEN UPDATE SET
    d.FORMADEPAGAMENTO = s.FORMADEPAGAMENTO,
    d.ID_BANCODOBRASIL = s.ID_BANCODOBRASIL
WHEN NOT MATCHED THEN INSERT (
    ID_FORMADEPAGAMENTO,
    FORMADEPAGAMENTO,
    ID_BANCODOBRASIL
) VALUES (
    s.ID_FORMADEPAGAMENTO,
    s.FORMADEPAGAMENTO,
    s.ID_BANCODOBRASIL
);

-- -----------------------------------------------------------------------------
-- 2) BSTAB_INTEGRACAO
-- Chave natural: (ID_SERVIDOR, ID_INTEGRACAO)
-- -----------------------------------------------------------------------------
MERGE INTO BSTAB_INTEGRACAO d
USING (
    SELECT '1' AS ID_SERVIDOR, 8 AS ID_INTEGRACAO, 'Cadastro de Veiculo' AS INTEGRACAO,
           TO_DATE('2026-04-29 22:22:40', 'YYYY-MM-DD HH24:MI:SS') AS DATAHORA_PROXIMA_ATUALIZACAO,
           30 AS INTERVALOMINUTOS, 'N' AS REALIZARINTEGRACAO, 'GET' AS METODO FROM DUAL
    UNION ALL SELECT '1', 3, 'Cadastro de Setor', TO_DATE('2026-04-30 20:45:33', 'YYYY-MM-DD HH24:MI:SS'), 1440, 'S', 'GET' FROM DUAL
    UNION ALL SELECT '1', 15, 'Get - Solicitacao de Despesa', TO_DATE('2026-04-29 20:44:33', 'YYYY-MM-DD HH24:MI:SS'), 10, 'N', 'GET' FROM DUAL
    UNION ALL SELECT '1', 5, 'Cadastro de Fornecedor', TO_DATE('2026-04-30 20:45:44', 'YYYY-MM-DD HH24:MI:SS'), 1440, 'S', 'GET' FROM DUAL
    UNION ALL SELECT '1', 16, 'Alterar Geolocalizacao do Cliente', TO_DATE('2026-04-29 20:44:37', 'YYYY-MM-DD HH24:MI:SS'), 0, 'S', 'POST' FROM DUAL
    UNION ALL SELECT '1', 9, 'Cadastro de Cliente', TO_DATE('2026-04-30 15:39:34', 'YYYY-MM-DD HH24:MI:SS'), 5, 'S', 'GET' FROM DUAL
    UNION ALL SELECT '1', 11, 'Cadastro Centro De Custo', TO_DATE('2026-04-30 20:45:43', 'YYYY-MM-DD HH24:MI:SS'), 1440, 'N', 'GET' FROM DUAL
    UNION ALL SELECT '1', 2, 'Cadastro de Filial', TO_DATE('2026-05-01 09:13:13', 'YYYY-MM-DD HH24:MI:SS'), 1440, 'S', 'GET' FROM DUAL
    UNION ALL SELECT '1', 18, 'Cadastro de Caixa Banco', TO_DATE('2026-04-30 09:42:53', 'YYYY-MM-DD HH24:MI:SS'), 1440, 'N', 'GET' FROM DUAL
    UNION ALL SELECT '1', 12, 'Solicitacao de Despesa - POST', TO_DATE('2026-04-29 20:44:45', 'YYYY-MM-DD HH24:MI:SS'), 0, 'S', 'POST' FROM DUAL
    UNION ALL SELECT '1', 10, 'Cadastro Conta Gerencial', TO_DATE('2026-04-30 20:45:53', 'YYYY-MM-DD HH24:MI:SS'), 1440, 'N', 'GET' FROM DUAL
    UNION ALL SELECT '1', 1, 'Cadastro de cliente Winthor', TO_DATE('2026-04-29 20:44:46', 'YYYY-MM-DD HH24:MI:SS'), 0, 'S', 'POST' FROM DUAL
    UNION ALL SELECT '1', 14, 'Enviar SMS', TO_DATE('2026-04-29 20:44:46', 'YYYY-MM-DD HH24:MI:SS'), 1440, 'N', 'POST' FROM DUAL
    UNION ALL SELECT '1', 17, 'Cadastro de Usuario - POST', TO_DATE('2026-04-29 20:44:48', 'YYYY-MM-DD HH24:MI:SS'), 0, 'S', 'POST' FROM DUAL
    UNION ALL SELECT '1', 13, 'Buscar SMS', TO_DATE('2026-04-29 20:44:48', 'YYYY-MM-DD HH24:MI:SS'), 1440, 'N', 'GET' FROM DUAL
    UNION ALL SELECT '1', 4, 'Cadastro de Usuario', TO_DATE('2026-04-30 15:37:29', 'YYYY-MM-DD HH24:MI:SS'), 5, 'S', 'GET' FROM DUAL
    UNION ALL SELECT '1', 7, 'Cadastro de Veiculo', TO_DATE('2026-04-29 20:44:51', 'YYYY-MM-DD HH24:MI:SS'), 1440, 'S', 'POST' FROM DUAL
    UNION ALL SELECT '1', 19, 'Vale', TO_DATE('2026-04-30 15:39:34', 'YYYY-MM-DD HH24:MI:SS'), 5, 'S', 'GET' FROM DUAL
) s
ON (
    d.ID_SERVIDOR = s.ID_SERVIDOR
    AND d.ID_INTEGRACAO = s.ID_INTEGRACAO
)
WHEN MATCHED THEN UPDATE SET
    d.INTEGRACAO = s.INTEGRACAO,
    d.DATAHORA_PROXIMA_ATUALIZACAO = s.DATAHORA_PROXIMA_ATUALIZACAO,
    d.INTERVALOMINUTOS = s.INTERVALOMINUTOS,
    d.REALIZARINTEGRACAO = s.REALIZARINTEGRACAO,
    d.METODO = s.METODO
WHEN NOT MATCHED THEN INSERT (
    ID_SERVIDOR,
    ID_INTEGRACAO,
    INTEGRACAO,
    DATAHORA_PROXIMA_ATUALIZACAO,
    INTERVALOMINUTOS,
    REALIZARINTEGRACAO,
    METODO
) VALUES (
    s.ID_SERVIDOR,
    s.ID_INTEGRACAO,
    s.INTEGRACAO,
    s.DATAHORA_PROXIMA_ATUALIZACAO,
    s.INTERVALOMINUTOS,
    s.REALIZARINTEGRACAO,
    s.METODO
);

-- -----------------------------------------------------------------------------
-- 3) BSTAB_INSTITUICAOBANCARIA
-- Chave natural: ID_BANCO
-- -----------------------------------------------------------------------------
MERGE INTO BSTAB_INSTITUICAOBANCARIA d
USING (
    SELECT 1 AS ID_BANCO, 'BANCO DO BRASIL S.A.' AS BANCO FROM DUAL
    UNION ALL SELECT 25, 'BANCO ALFA S.A.' FROM DUAL
    UNION ALL SELECT 33, 'BANCO SANTANDER (BRASIL) S.A.' FROM DUAL
    UNION ALL SELECT 41, 'BANCO DO ESTADO DO RIO GRANDE DO SUL S.A. (BANRISUL)' FROM DUAL
    UNION ALL SELECT 77, 'BANCO INTER S.A.' FROM DUAL
    UNION ALL SELECT 104, 'CAIXA ECONOMICA FEDERAL' FROM DUAL
    UNION ALL SELECT 121, 'BANCO AGIBANK S.A.' FROM DUAL
    UNION ALL SELECT 218, 'BANCO BS2 S.A.' FROM DUAL
    UNION ALL SELECT 237, 'BANCO BRADESCO S.A.' FROM DUAL
    UNION ALL SELECT 260, 'NU PAGAMENTOS S.A. (NUBANK)' FROM DUAL
    UNION ALL SELECT 341, 'BANCO ITAU S.A.' FROM DUAL
    UNION ALL SELECT 389, 'BANCO MERCANTIL DO BRASIL S.A.' FROM DUAL
    UNION ALL SELECT 422, 'BANCO SAFRA S.A.' FROM DUAL
    UNION ALL SELECT 748, 'BANCO COOPERATIVO SICREDI S.A.' FROM DUAL
    UNION ALL SELECT 756, 'BANCO COOPERATIVO DO BRASIL S.A. (SICOOB)' FROM DUAL
) s
ON (d.ID_BANCO = s.ID_BANCO)
WHEN MATCHED THEN UPDATE SET
    d.BANCO = s.BANCO
WHEN NOT MATCHED THEN INSERT (
    ID_BANCO,
    BANCO
) VALUES (
    s.ID_BANCO,
    s.BANCO
);
