DECLARE
  v_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_exists
    FROM ALL_TABLES
   WHERE OWNER = 'BELLASISTEMAS'
     AND TABLE_NAME = 'BSTAB_SOLICITADESPESA_HISTORICO';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE BELLASISTEMAS.BSTAB_SOLICITADESPESA_HISTORICO (
        ID_HISTORICO      NUMBER(19,0)    NOT NULL,
        NUMSOLICITACAO    NUMBER(19,0)    NOT NULL,
        ID_GRUPO_EMPRESA  NUMBER(19,0)    NULL,
        ETAPA             VARCHAR2(100)   NOT NULL,
        STATUS_ANTES      VARCHAR2(100)   NULL,
        STATUS_DEPOIS     VARCHAR2(100)   NOT NULL,
        ID_USUARIO        NUMBER(19,0)    NULL,
        NOME_USUARIO      VARCHAR2(200)   NULL,
        OBSERVACAO        CLOB            NULL,
        DATAHORA          DATE            DEFAULT SYSDATE NOT NULL
      )';
  END IF;
END;
/

DECLARE
  v_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_exists
    FROM ALL_CONSTRAINTS
   WHERE OWNER = 'BELLASISTEMAS'
     AND TABLE_NAME = 'BSTAB_SOLICITADESPESA_HISTORICO'
     AND CONSTRAINT_NAME = 'PK_BSTAB_SOLICDESP_HIST';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE '
      ALTER TABLE BELLASISTEMAS.BSTAB_SOLICITADESPESA_HISTORICO
      ADD CONSTRAINT PK_BSTAB_SOLICDESP_HIST PRIMARY KEY (ID_HISTORICO)';
  END IF;
END;
/

DECLARE
  v_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_exists
    FROM ALL_SEQUENCES
   WHERE SEQUENCE_OWNER = 'BELLASISTEMAS'
     AND SEQUENCE_NAME = 'SEQ_SOLICITADESPESA_HISTORICO';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE SEQUENCE BELLASISTEMAS.SEQ_SOLICITADESPESA_HISTORICO
      START WITH 1
      INCREMENT BY 1
      NOCACHE';
  END IF;
END;
/

DECLARE
  v_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_exists
    FROM ALL_INDEXES
   WHERE OWNER = 'BELLASISTEMAS'
     AND TABLE_NAME = 'BSTAB_SOLICITADESPESA_HISTORICO'
     AND INDEX_NAME = 'IX_SOLICDESP_HIST_SOLIC_DATA';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE INDEX BELLASISTEMAS.IX_SOLICDESP_HIST_SOLIC_DATA
      ON BELLASISTEMAS.BSTAB_SOLICITADESPESA_HISTORICO (NUMSOLICITACAO, DATAHORA)';
  END IF;
END;
/
