-- =============================================================================
-- V1.4 - CREATE MISSING SEQUENCES
-- Cria sequences ausentes de forma idempotente.
-- =============================================================================

DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='DFSEQ_PCCORREN_NUMTRANSBAIXA'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE DFSEQ_PCCORREN_NUMTRANSBAIXA INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='DFSEQ_PCCRECLI'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE DFSEQ_PCCRECLI INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='DFSEQ_PCCRECLI_NUMCRED'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE DFSEQ_PCCRECLI_NUMCRED INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_BSTAB_USUARIO_ID'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_BSTAB_USUARIO_ID INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_BSTAB_VALE_ID'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_BSTAB_VALE_ID INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_BS_EXCA_ARQ'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_BS_EXCA_ARQ INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_BS_EXCA_HEADER_AQR'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_BS_EXCA_HEADER_AQR INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_BS_EXCA_HEADER_LOTE'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_BS_EXCA_HEADER_LOTE INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_BS_EXCA_REG'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_BS_EXCA_REG INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_BS_EXCA_TRAILERARQ'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_BS_EXCA_TRAILERARQ INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_BS_EXCA_TRAILERLOTE'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_BS_EXCA_TRAILERLOTE INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_FINANCEIRO_LANCAMENTO'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_FINANCEIRO_LANCAMENTO INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
DECLARE v_exists NUMBER := 0; BEGIN SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_WEBHOOK_PIX_BOLETO'; IF v_exists=0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_WEBHOOK_PIX_BOLETO INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER'; END IF; END;
/
