-- =============================================================================
-- V1.7 - ATIVACAO MOBILE VIA QR CODE
-- Cria estrutura para geracao/controle de token de ativacao mobile
-- =============================================================================

DECLARE
  v_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_exists
    FROM USER_TABLES
   WHERE TABLE_NAME = 'BSTAB_MOBILE_ATIVACAO';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE BSTAB_MOBILE_ATIVACAO (
        ID_ATIVACAO           NUMBER(18)      NOT NULL,
        ID_EMPRESA            VARCHAR2(30)    NOT NULL,
        RAZAOSOCIAL           VARCHAR2(255),
        ID_USUARIO_CRIACAO    NUMBER(18)      NOT NULL,
        ID_USUARIO_ALTERACAO  NUMBER(18),
        API_BASE_URL          VARCHAR2(500)   NOT NULL,
        CODIGO_ATIVACAO       VARCHAR2(30)    NOT NULL,
        TOKEN_HASH            VARCHAR2(64)    NOT NULL,
        STATUS                CHAR(1)         DEFAULT ''P'' NOT NULL,
        DT_CRIACAO            DATE            DEFAULT SYSDATE NOT NULL,
        DT_EXPIRACAO          DATE            NOT NULL,
        DT_UTILIZACAO         DATE,
        DT_ALTERACAO          DATE,
        DISPOSITIVO           VARCHAR2(200),
        IP_UTILIZACAO         VARCHAR2(80),
        CONSTRAINT PK_BSTAB_MOBILE_ATIVACAO PRIMARY KEY (ID_ATIVACAO),
        CONSTRAINT UK_BSTAB_MOBILE_ATIVACAO_HASH UNIQUE (TOKEN_HASH),
        CONSTRAINT CK_BSTAB_MOBILE_ATIVACAO_ST CHECK (STATUS IN (''P'',''U'',''R''))
      )
    ';
  END IF;
END;
/

DECLARE
  v_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_exists
    FROM USER_SEQUENCES
   WHERE SEQUENCE_NAME = 'SEQ_BSTAB_MOBILE_ATIVACAO';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_BSTAB_MOBILE_ATIVACAO INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER';
  END IF;
END;
/

DECLARE
  v_exists NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_exists
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'IDX_BSTAB_MOBILE_ATV_EMP';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_BSTAB_MOBILE_ATV_EMP ON BSTAB_MOBILE_ATIVACAO (ID_EMPRESA, STATUS, DT_EXPIRACAO)';
  END IF;
END;
/

MERGE INTO BSTAB_ROTINAS d
USING (
    SELECT 203 AS ID_ROTINA,
           'Ativacao Mobile (QR Code)' AS ROTINA,
           '1.0' AS VERSAO,
           TIMESTAMP'2026-05-01 00:00:00' AS DTCRIACAO,
           CAST(NULL AS TIMESTAMP) AS DTATUALIZACAO,
           1 AS ID_MODULO,
           '/Configuracao/MobileAtivacao' AS CAMINHO,
           NULL AS SCREEN
      FROM DUAL
) s
ON (d.ID_ROTINA = s.ID_ROTINA)
WHEN MATCHED THEN UPDATE SET
    d.ROTINA        = s.ROTINA,
    d.VERSAO        = s.VERSAO,
    d.DTCRIACAO     = s.DTCRIACAO,
    d.DTATUALIZACAO = s.DTATUALIZACAO,
    d.ID_MODULO     = s.ID_MODULO,
    d.CAMINHO       = s.CAMINHO,
    d.SCREEN        = s.SCREEN
WHEN NOT MATCHED THEN INSERT (
    ID_ROTINA,
    ROTINA,
    VERSAO,
    DTCRIACAO,
    DTATUALIZACAO,
    ID_MODULO,
    CAMINHO,
    SCREEN
) VALUES (
    s.ID_ROTINA,
    s.ROTINA,
    s.VERSAO,
    s.DTCRIACAO,
    s.DTATUALIZACAO,
    s.ID_MODULO,
    s.CAMINHO,
    s.SCREEN
);

MERGE INTO BSTAB_ROTINA_SUBPERMISSOES d
USING (
    SELECT 20301 AS ID_SUBPERMISSAO, 203 AS ID_ROTINA, 'Gerar QR de ativacao' AS DESCRICAO, 1 AS ORDEM, 'S' AS ATIVO, TIMESTAMP'2026-05-01 00:00:00' AS DT_CADASTRO FROM DUAL
    UNION ALL
    SELECT 20302, 203, 'Revogar ativacao', 2, 'S', TIMESTAMP'2026-05-01 00:00:00' FROM DUAL
) s
ON (d.ID_SUBPERMISSAO = s.ID_SUBPERMISSAO)
WHEN MATCHED THEN UPDATE SET
    d.ID_ROTINA = s.ID_ROTINA,
    d.DESCRICAO = s.DESCRICAO,
    d.ORDEM = s.ORDEM,
    d.ATIVO = s.ATIVO
WHEN NOT MATCHED THEN INSERT (
    ID_SUBPERMISSAO,
    ID_ROTINA,
    DESCRICAO,
    ORDEM,
    ATIVO,
    DT_CADASTRO,
    DT_ALTERACAO
) VALUES (
    s.ID_SUBPERMISSAO,
    s.ID_ROTINA,
    s.DESCRICAO,
    s.ORDEM,
    s.ATIVO,
    s.DT_CADASTRO,
    NULL
);
